<?php

$site = require __DIR__.'/../en/site.php';

return array_replace_recursive($site, [
    'language' => ['label' => '语言', 'choose' => '选择语言'],
    'nav' => ['home' => '首页', 'products' => '产品', 'categories' => '分类', 'about' => '关于我们', 'certificates' => '认证', 'contact' => '联系我们', 'contents' => '故事'],
    'footer' => ['explore' => '探索', 'contact' => '联系我们', 'social' => '社交媒体', 'reach_us' => '联系我们', 'tagline' => '分享美好。', 'description' => '来自自然的美好想法。每一口都感受美好。'],
    'actions' => ['skip_to_content' => '跳至内容', 'open_menu' => '打开或关闭菜单', 'view_product' => '查看产品', 'all_products' => '所有产品', 'scroll_down' => '向下滚动', 'discover' => '探索', 'discover_story' => '了解我们的故事', 'open_document' => '打开文件', 'view_document' => '查看文件', 'contact_us' => '联系我们', 'get_directions' => '获取路线', 'view_map' => '在地图中查看', 'send_message' => '发送消息', 'learn_more' => '了解更多', 'close' => '关闭'],
    'catalog' => ['default_category' => 'Nuttime 精选', 'category' => '分类', 'products_count' => ':count 件产品', 'category_count' => '分类 / :count 件产品', 'empty' => '我们的精选产品即将呈现。', 'category_empty' => '该分类暂时没有在售产品。'],
    'home' => ['banners_label' => 'Nuttime 精选', 'banner_one_kicker' => '新一代美味', 'banner_one_title' => '重新发现<br>开心果。', 'banner_two_kicker' => '陪伴每一天', 'banner_two_title' => '一勺之间<br>感受美好。', 'intro' => '我们将优质坚果与简单配料，化为<em>一天中最愉悦的时刻。</em>', 'featured_kicker' => '精心挑选', 'featured_title' => '精选<br><em>风味。</em>', 'categories_kicker' => '分类', 'categories_title' => '找到令你感到<br><em>美好的选择。</em>', 'story_kicker' => '我们是谁', 'story_title' => '好产品，<br><em>好感受，</em><br>好生活。', 'story_copy' => 'Nuttime 让精心挑选的坚果展现天然本色，等待你每天重新发现。', 'quality_kicker' => '安心制造', 'quality_title' => '品质见于<br><em>每一个细节。</em>', 'social_kicker' => '每日灵感', 'social_title' => '近距离关注<br><em>Nuttime。</em>', 'instagram' => '打开 Instagram'],
    'final_cta' => ['kicker' => '认识 NUTTIME', 'title' => '陪伴一天中<br><em>每个美好时刻。</em>'],
    'product' => ['detail_label' => 'Nuttime 精选', 'detail_copy' => '天然原料、细致生产，带来令人愉悦的味觉体验。', 'whatsapp' => '通过 WhatsApp 咨询', 'image' => '产品图片 :number', 'breadcrumbs' => '产品路径', 'ingredients_kicker' => '产品信息', 'ingredients' => '配料', 'allergens' => '过敏原信息：', 'nutrition_kicker' => '营养成分', 'nutrition' => '一目了然', 'packaging_kicker' => 'B2B / 物流', 'packaging' => '包装与物流', 'packaging_copy' => '零售与工业包装信息经过结构化整理，便于规划发运。'],
    'static' => ['about_kicker' => '关于 NUTTIME', 'about_title' => '我们<em>是谁？</em>', 'about_copy' => '我们是一家由四口之家拥有和经营的小型家族企业。我们怀着生产高品质食品的愿望出发，致力于让每一件产品既美味又营养。', 'who_kicker' => '我们是谁', 'who_title' => '一家小型家族企业。', 'who_copy_one' => '虽然十年间我们已增长了四百倍，但仍然觉得自己是一家小型家族企业。', 'who_copy_two' => '这种感觉让我们感到安心。', 'mission_kicker' => '我们的使命', 'mission_title' => '用心培育美好。', 'mission_copy_one' => '我们为能成为建设更快乐、更健康、更包容、更安全社会的重要一环而自豪，并致力于成为世界上最美味的榛子、杏仁和花生酱品牌之一。', 'mission_copy_two' => '我们尽可能以简单、细致和周到的方式对待真主完美创造并赐予我们的食材。', 'mission_copy_three' => '我们尊重土地、天空以及两者之间的一切。作为食品生产商，我们深知有责任努力创造积极影响。', 'mission_donation_before' => '通过本网站购买产品所得的全部利润都以您的名义捐献；我们劳动所得则以我们挚爱的儿子', 'mission_donation_after' => '之名捐献给孤儿及孤儿家庭。', 'mission_quote' => '“在清算之日，微尘之重也将昭然若揭。”', 'company_kicker' => '联系 / 公司信息', 'company_title' => '我们在这里。', 'phone_label' => '电话', 'location_label' => '地点', 'address_label' => '地址', 'certificates_kicker' => '安心制造', 'certificates_title' => '我们的品质<br><em>认证。</em>', 'certificates_copy' => '在这里查看我们的最新认证。', 'certificate' => '认证', 'certificates_empty' => '我们的品质认证即将展示于此。'],
    'contact' => ['kicker' => '让我们合作', 'title' => '一起说声<br><em>你好。</em>', 'copy' => '如需了解产品、合作或报价，请联系我们。', 'section' => '联系', 'name' => '姓名', 'email' => '电子邮箱', 'message' => '您的留言', 'success' => '感谢您的留言，我们的团队将尽快回复。'],
    'factory' => ['kicker' => '工厂 / 生产基地', 'fallback_name' => '我们的生产基地', 'address_label' => '地址', 'phone_label' => '电话', 'email_label' => '电子邮箱', 'map_title' => 'Nuttime 工厂位置', 'map_copy' => '在 Google 地图<br>查看位置。'],
    'errors' => ['home' => '返回首页', 'products' => '查看产品', '403' => ['heading' => '无权访问', 'message' => '您无权查看此页面。'], '404' => ['heading' => '页面未找到', 'message' => '您查找的页面不存在或可能已移动。'], '419' => ['heading' => '会话已过期', 'message' => '请刷新页面后重试。'], '500' => ['heading' => '出现问题', 'message' => '我们的技术团队已收到通知，请稍后再试。']],
]);
