<?php

$site = require __DIR__.'/../tr/site.php';

return array_replace_recursive($site, [
    'language' => ['label' => 'Language', 'choose' => 'Choose language'],
    'nav' => ['home' => 'Home', 'products' => 'Products', 'categories' => 'Categories', 'about' => 'About us', 'certificates' => 'Certificates', 'contact' => 'Contact', 'contents' => 'Stories'],
    'footer' => ['explore' => 'Explore', 'contact' => 'Contact', 'social' => 'Social', 'reach_us' => 'Get in touch', 'tagline' => 'Share what is good.', 'description' => 'A good idea from nature. Feel good in every bite.'],
    'actions' => ['open_menu' => 'Open or close menu', 'view_product' => 'View product', 'all_products' => 'All products', 'scroll_down' => 'Scroll down', 'discover' => 'Discover', 'discover_story' => 'Discover our story', 'open_document' => 'Open document', 'view_document' => 'View document', 'contact_us' => 'Contact us', 'get_directions' => 'Get directions', 'view_map' => 'View on map', 'send_message' => 'Send message', 'learn_more' => 'Learn more'],
    'catalog' => ['default_category' => 'Nuttime selection', 'category' => 'category', 'products_count' => ':count products', 'category_count' => 'CATEGORY / :count PRODUCTS', 'empty' => 'Our selection will be here soon.', 'category_empty' => 'There are no active products in this category yet.'],
    'meta' => ['home' => ['title' => 'Nuttime', 'description' => 'Discover rich nut flavours made from simple ingredients with Nuttime.'], 'products' => ['title' => 'Nuttime Products', 'description' => 'Discover Nuttime nut butters and our carefully made product selection.'], 'about' => ['title' => 'About Nuttime', 'description' => 'Discover Nuttime’s approach to production and quality.'], 'certificates' => ['title' => 'Nuttime Certificates', 'description' => 'Explore Nuttime quality certificates and production standards.'], 'contact' => ['title' => 'Contact Nuttime', 'description' => 'Contact Nuttime for partnerships and product enquiries.'], 'contents' => ['title' => 'Nuttime Stories', 'description' => 'Recipes, news and stories from the Nuttime world.']],
    'hero' => ['yer-fistigi-ezmesi' => ['eyebrow' => 'NUTTIME • 52% PEANUTS', 'title' => 'THE RICHEST FORM OF PEANUT'], 'findik-kremasi' => ['eyebrow' => 'NUTTIME • 45% HAZELNUTS', 'title' => 'THE ROASTED RICHNESS OF HAZELNUT'], 'antep-fistikli-kremasi' => ['eyebrow' => 'NUTTIME • 42% PISTACHIOS', 'title' => 'THE RICHEST FORM OF PISTACHIO'], 'badem-unu' => ['eyebrow' => 'NUTTIME • 45% ALMONDS', 'title' => 'THE ELEGANT, RICH TEXTURE OF ALMOND'], 'seker-ilavesiz-yer-fistigi-ezmesi' => ['eyebrow' => 'NUTTIME • NO ADDED SUGAR • 72%', 'title' => 'SIMPLER, RICHER PEANUT'], 'hindistan-cevizi-ezmesi' => ['eyebrow' => 'NUTTIME • 42% COCONUT', 'title' => 'A FRESH, CREAMY TEXTURE']],
    'home' => ['banners_label' => 'Nuttime selection', 'banner_one_kicker' => 'A NEW GENERATION OF TASTE', 'banner_one_title' => 'Rediscover<br>pistachio.', 'banner_two_kicker' => 'FOR EVERY DAY', 'banner_two_title' => 'Feel good<br>in one spoonful.', 'intro' => 'We turn fine nuts and simple ingredients into <em>the most enjoyable moment of your day.</em>', 'featured_kicker' => 'CAREFULLY SELECTED', 'featured_title' => 'Featured<br><em>flavours.</em>', 'categories_kicker' => 'CATEGORIES', 'categories_title' => 'Find what<br><em>feels good.</em>', 'moment_kicker' => 'MORE THAN A JAR', 'moment_title' => 'A good companion for<br><em>every taste and rhythm.</em>', 'story_kicker' => 'WHO WE ARE', 'story_title' => 'Good products,<br><em>good feelings,</em><br>a good life.', 'story_copy' => 'Nuttime prepares the natural character of carefully selected nuts for you to rediscover every day.', 'quality_kicker' => 'MADE WITH CONFIDENCE', 'quality_title' => 'Quality in<br><em>every detail.</em>', 'social_kicker' => 'DAILY INSPIRATION', 'social_title' => 'Follow Nuttime<br><em>more closely.</em>', 'instagram' => 'Open Instagram'],
    'final_cta' => ['kicker' => 'MEET NUTTIME', 'title' => 'A good companion for<br><em>every moment of the day.</em>'],
    'product' => ['detail_label' => 'Nuttime selection', 'detail_copy' => 'Natural ingredients, careful production and a flavour experience that feels good.', 'whatsapp' => 'Ask on WhatsApp', 'related_kicker' => 'DISCOVER THESE TOO', 'related_title' => 'More flavours<br><em>from the selection.</em>', 'image' => 'Product image :number'],
    'static' => ['about_kicker' => 'ABOUT NUTTIME', 'about_title' => 'Bringing what is good<br><em>into everyday life.</em>', 'about_copy' => 'The simple approach behind a good idea from nature.', 'about_lead' => 'Nuttime brings the finest flavours from nature together with the rhythm of modern life.', 'approach_kicker' => 'A SIMPLE APPROACH', 'approach_title' => 'Care in sourcing,<br><em>care in making.</em>', 'approach_copy' => 'For us, good flavour comes from good ingredients, the right process and a sincere approach.', 'meet_us' => 'Meet us', 'certificates_kicker' => 'MADE WITH CONFIDENCE', 'certificates_title' => 'Our quality<br><em>certificates.</em>', 'certificates_copy' => 'Explore our current certificates here.', 'certificate' => 'CERTIFICATE', 'certificates_empty' => 'Our quality certificates will be available here soon.'],
    'contact' => ['kicker' => 'LET’S WORK TOGETHER', 'title' => 'Let’s say<br><em>hello.</em>', 'copy' => 'Contact us for products, partnerships or quote requests.', 'section' => 'CONTACT', 'name' => 'Full name', 'email' => 'Email', 'message' => 'Your message', 'success' => 'Thank you for your message. Our team will get back to you shortly.'],
    'factory' => ['kicker' => 'FACTORY / PRODUCTION FACILITY', 'fallback_name' => 'Our production facility', 'address_label' => 'ADDRESS', 'phone_label' => 'PHONE', 'email_label' => 'EMAIL', 'map_title' => 'Nuttime factory location', 'map_copy' => 'View the location<br>on Google Maps.'],
    'errors' => ['home' => 'Back to home', 'products' => 'Browse products', '403' => ['heading' => 'Access denied', 'message' => 'You do not have permission to view this page.'], '404' => ['heading' => 'Page not found', 'message' => 'The page you are looking for does not exist or may have moved.'], '419' => ['heading' => 'Session expired', 'message' => 'Please refresh the page and try again.'], '500' => ['heading' => 'Something went wrong', 'message' => 'Our technical team has been notified. Please try again shortly.']],
]);
