<?php

$site = require __DIR__.'/../tr/site.php';

return array_replace_recursive($site, [
    'language' => ['label' => 'Language', 'choose' => 'Choose language'],
    'nav' => ['home' => 'Home', 'products' => 'Products', 'categories' => 'Categories', 'about' => 'About us', 'certificates' => 'Certificates', 'contact' => 'Contact', 'contents' => 'Stories'],
    'footer' => ['explore' => 'Explore', 'contact' => 'Contact', 'social' => 'Social', 'reach_us' => 'Get in touch', 'tagline' => 'Share what is good.', 'description' => 'A good idea from nature. Feel good in every bite.'],
    'actions' => ['skip_to_content' => 'Skip to content', 'open_menu' => 'Open or close menu', 'view_product' => 'View product', 'all_products' => 'All products', 'scroll_down' => 'Scroll down', 'discover' => 'Discover', 'discover_story' => 'Discover our story', 'open_document' => 'Open document', 'view_document' => 'View document', 'contact_us' => 'Contact us', 'get_directions' => 'Get directions', 'view_map' => 'View on map', 'send_message' => 'Send message', 'learn_more' => 'Learn more', 'close' => 'Close'],
    'catalog' => ['default_category' => 'Nuttime selection', 'category' => 'category', 'products_count' => ':count products', 'category_count' => 'CATEGORY / :count PRODUCTS', 'empty' => 'Our selection will be here soon.', 'category_empty' => 'There are no active products in this category yet.'],
    'meta' => ['home' => ['title' => 'Nuttime', 'description' => 'Discover rich nut flavours made from simple ingredients with Nuttime.'], 'products' => ['title' => 'Nuttime Products', 'description' => 'Discover Nuttime nut butters and our carefully made product selection.'], 'about' => ['title' => 'About Nuttime', 'description' => 'Discover Nuttime’s approach to production and quality.'], 'certificates' => ['title' => 'Nuttime Certificates', 'description' => 'Explore Nuttime quality certificates and production standards.'], 'contact' => ['title' => 'Contact Nuttime', 'description' => 'Contact Nuttime for partnerships and product enquiries.'], 'contents' => ['title' => 'Nuttime Stories', 'description' => 'Recipes, news and stories from the Nuttime world.']],
    'hero' => ['yer-fistigi-ezmesi' => ['eyebrow' => 'NUTTIME • 52% PEANUTS', 'title' => 'THE RICHEST FORM OF PEANUT'], 'findik-kremasi' => ['eyebrow' => 'NUTTIME • 45% HAZELNUTS', 'title' => 'THE ROASTED RICHNESS OF HAZELNUT'], 'antep-fistikli-kremasi' => ['eyebrow' => 'NUTTIME • 42% PISTACHIOS', 'title' => 'THE RICHEST FORM OF PISTACHIO'], 'badem-unu' => ['eyebrow' => 'NUTTIME • 45% ALMONDS', 'title' => 'THE ELEGANT, RICH TEXTURE OF ALMOND'], 'seker-ilavesiz-yer-fistigi-ezmesi' => ['eyebrow' => 'NUTTIME • NO ADDED SUGAR • 72%', 'title' => 'SIMPLER, RICHER PEANUT'], 'hindistan-cevizi-ezmesi' => ['eyebrow' => 'NUTTIME • 42% COCONUT', 'title' => 'A FRESH, CREAMY TEXTURE']],
    'home' => ['banners_label' => 'Nuttime selection', 'banner_one_kicker' => 'A NEW GENERATION OF TASTE', 'banner_one_title' => 'Rediscover<br>pistachio.', 'banner_two_kicker' => 'FOR EVERY DAY', 'banner_two_title' => 'Feel good<br>in one spoonful.', 'intro' => 'We turn fine nuts and simple ingredients into <em>the most enjoyable moment of your day.</em>', 'featured_kicker' => 'CAREFULLY SELECTED', 'featured_title' => 'Featured<br><em>flavours.</em>', 'categories_kicker' => 'CATEGORIES', 'categories_title' => 'Find what<br><em>feels good.</em>', 'moment_kicker' => 'MORE THAN A JAR', 'moment_title' => 'A good companion for<br><em>every taste and rhythm.</em>', 'story_kicker' => 'WHO WE ARE', 'story_title' => 'Good products,<br><em>good feelings,</em><br>a good life.', 'story_copy' => 'Nuttime prepares the natural character of carefully selected nuts for you to rediscover every day.', 'quality_kicker' => 'MADE WITH CONFIDENCE', 'quality_title' => 'Quality in<br><em>every detail.</em>', 'social_kicker' => 'DAILY INSPIRATION', 'social_title' => 'Follow Nuttime<br><em>more closely.</em>', 'instagram' => 'Open Instagram'],
    'final_cta' => ['kicker' => 'MEET NUTTIME', 'title' => 'A good companion for<br><em>every moment of the day.</em>'],
    'product' => ['detail_label' => 'Nuttime selection', 'detail_copy' => 'Natural ingredients, careful production and a flavour experience that feels good.', 'whatsapp' => 'Ask on WhatsApp', 'related_kicker' => 'DISCOVER THESE TOO', 'related_title' => 'More flavours<br><em>from the selection.</em>', 'image' => 'Product image :number', 'breadcrumbs' => 'Product trail', 'ingredients_kicker' => 'PRODUCT INFORMATION', 'ingredients' => 'Ingredients', 'allergens' => 'Allergen information: ', 'nutrition_kicker' => 'NUTRITIONAL VALUES', 'nutrition' => 'At a glance', 'packaging_kicker' => 'B2B / LOGISTICS', 'packaging' => 'Packaging & logistics', 'packaging_copy' => 'Retail and industrial packaging details are structured for shipment planning.', 'nutrition_fields' => ['energy' => 'Energy (kJ/kcal)', 'fat' => 'Fat (%)', 'saturated_fat' => 'Saturated fatty acids (g)', 'trans_fat' => 'Trans fat (g)', 'carbohydrates' => 'Carbohydrates (g)', 'sugar' => 'Sugar (g)', 'fibre' => 'Fibre (g)', 'protein' => 'Protein (g)', 'salt' => 'Salt (g)'], 'packaging_groups' => ['general' => 'Packaging', 'jar' => 'Jar', 'carton' => 'Carton', 'pallet' => 'Carton pallet', 'industrial' => 'Industrial pail / Europallet', 'dimensions' => 'Technical dimensions'], 'packaging_fields' => ['net_weight' => 'Net weight', 'gross_weight' => 'Gross weight', 'diameter' => 'Diameter', 'height' => 'Height', 'units' => 'Units per carton', 'buckets_on_pallet' => 'Pails per pallet', 'dimensions' => 'Dimensions', 'dimensions_inches' => 'Inch equivalent', 'cartons' => 'Cartons per pallet', 'type' => 'Pallet type', 'loaded_height' => 'Loaded pallet height', 'loaded_height_inches' => 'Inch equivalent', 'd1' => 'D1', 'd2' => 'D2', 'd3' => 'D3', 'h' => 'H']],
    'static' => ['about_kicker' => 'ABOUT NUTTIME', 'about_title' => 'Who <em>are we?</em>', 'about_copy' => 'Our company is a small family business owned and run by a family of four. We set out with the idea of striving to produce food of outstanding quality. We develop every one of our products to be delicious and nutritious.', 'about_lead' => 'We believe that nutrition is the foundation of health.', 'who_kicker' => 'WHO WE ARE', 'who_title' => 'A small family business.', 'who_copy_one' => 'Although we have grown 400-fold in 10 years on the path we began with this belief, we still feel like a small family business.', 'who_copy_two' => 'That feeling is good for us.', 'mission_kicker' => 'OUR MISSION', 'mission_title' => 'Growing what is good with care.', 'mission_copy_one' => 'We are proud to be an important part of the solution in building a happier, healthier, more inclusive and safer society for everyone, while working towards becoming one of the world’s most delicious hazelnut, almond and peanut butter brands.', 'mission_copy_two' => 'We handle the ingredients Allah created perfectly and presented to us as simply, carefully and thoughtfully as possible.', 'mission_copy_three' => 'We respect the earth, the sky and everything in between. As a food producer, we are conscious of our responsibility to strive for a positive impact.', 'mission_donation_before' => 'All profits from products purchased through this website are dedicated in your name; the income from labour is dedicated, in the name of our beloved son', 'mission_donation_name' => 'Oğuzhan Kuş', 'mission_donation_after' => 'to orphans and orphaned families.', 'mission_quote' => '“On the Day of Reckoning, even an atom’s weight will be made manifest.”', 'company_kicker' => 'CONTACT / COMPANY INFORMATION', 'company_title' => 'We are here.', 'phone_label' => 'PHONE', 'location_label' => 'LOCATION', 'address_label' => 'ADDRESS', 'certificates_kicker' => 'MADE WITH CONFIDENCE', 'certificates_title' => 'Our quality<br><em>certificates.</em>', 'certificates_copy' => 'Explore our current certificates here.', 'certificate' => 'CERTIFICATE', 'certificates_empty' => 'Our quality certificates will be available here soon.'],
    'contact' => ['kicker' => 'LET’S WORK TOGETHER', 'title' => 'Let’s say<br><em>hello.</em>', 'copy' => 'Contact us for products, partnerships or quote requests.', 'section' => 'CONTACT', 'name' => 'Full name', 'email' => 'Email', 'message' => 'Your message', 'success' => 'Thank you for your message. Our team will get back to you shortly.'],
    'factory' => ['kicker' => 'FACTORY / PRODUCTION FACILITY', 'fallback_name' => 'Our production facility', 'address_label' => 'ADDRESS', 'phone_label' => 'PHONE', 'email_label' => 'EMAIL', 'map_title' => 'Nuttime factory location', 'map_copy' => 'View the location<br>on Google Maps.'],
    'errors' => ['home' => 'Back to home', 'products' => 'Browse products', '403' => ['heading' => 'Access denied', 'message' => 'You do not have permission to view this page.'], '404' => ['heading' => 'Page not found', 'message' => 'The page you are looking for does not exist or may have moved.'], '419' => ['heading' => 'Session expired', 'message' => 'Please refresh the page and try again.'], '500' => ['heading' => 'Something went wrong', 'message' => 'Our technical team has been notified. Please try again shortly.']],
]);
