<?php

$site = require __DIR__.'/../en/site.php';

return array_replace_recursive($site, [
    'language' => ['label' => 'Langue', 'choose' => 'Choisir une langue'],
    'nav' => ['home' => 'Accueil', 'products' => 'Produits', 'categories' => 'Catégories', 'about' => 'À propos', 'certificates' => 'Certificats', 'contact' => 'Contact', 'contents' => 'Articles'],
    'footer' => ['explore' => 'Découvrir', 'contact' => 'Contact', 'social' => 'Réseaux sociaux', 'reach_us' => 'Nous contacter', 'tagline' => 'Partagez ce qui est bon.', 'description' => 'Une belle idée venue de la nature. Se sentir bien à chaque bouchée.'],
    'actions' => ['open_menu' => 'Ouvrir ou fermer le menu', 'view_product' => 'Voir le produit', 'all_products' => 'Tous les produits', 'scroll_down' => 'Faire défiler', 'discover' => 'Découvrir', 'discover_story' => 'Découvrir notre histoire', 'open_document' => 'Ouvrir le document', 'view_document' => 'Voir le document', 'contact_us' => 'Nous contacter', 'get_directions' => 'Itinéraire', 'view_map' => 'Voir sur la carte', 'send_message' => 'Envoyer le message', 'learn_more' => 'Découvrir', 'close' => 'Fermer'],
    'catalog' => ['default_category' => 'Sélection Nuttime', 'category' => 'catégorie', 'products_count' => ':count produits', 'category_count' => 'CATÉGORIE / :count PRODUITS', 'empty' => 'Notre sélection arrivera bientôt.', 'category_empty' => 'Aucun produit actif dans cette catégorie pour le moment.'],
    'meta' => ['home' => ['title' => 'Nuttime', 'description' => 'Découvrez avec Nuttime des saveurs de fruits à coque intenses, issues d’ingrédients simples.'], 'products' => ['title' => 'Produits Nuttime', 'description' => 'Découvrez les pâtes de fruits à coque Nuttime et notre sélection préparée avec soin.'], 'about' => ['title' => 'À propos de Nuttime', 'description' => 'Découvrez l’approche de Nuttime en matière de production et de qualité.'], 'certificates' => ['title' => 'Certificats Nuttime', 'description' => 'Découvrez les certificats qualité et les standards de production Nuttime.'], 'contact' => ['title' => 'Contacter Nuttime', 'description' => 'Contactez Nuttime pour vos partenariats et demandes de produits.']],
    'home' => ['banners_label' => 'Sélections Nuttime', 'banner_one_kicker' => 'UNE NOUVELLE GÉNÉRATION DE GOÛT', 'banner_one_title' => 'Redécouvrez<br>la pistache.', 'banner_two_kicker' => 'POUR CHAQUE JOUR', 'banner_two_title' => 'Se sentir bien<br>en une cuillerée.', 'intro' => 'Nous transformons de bons fruits à coque et des ingrédients simples en <em>l’un des plus beaux moments de votre journée.</em>', 'featured_kicker' => 'SÉLECTIONNÉ AVEC SOIN', 'featured_title' => 'Saveurs<br><em>à découvrir.</em>', 'categories_kicker' => 'CATÉGORIES', 'categories_title' => 'Trouvez ce qui vous<br><em>fait du bien.</em>', 'story_kicker' => 'QUI SOMMES-NOUS ?', 'story_title' => 'De bons produits,<br><em>de bonnes sensations,</em><br>une belle vie.', 'story_copy' => 'Nuttime révèle chaque jour le caractère naturel de fruits à coque soigneusement sélectionnés.', 'quality_kicker' => 'FABRIQUÉ AVEC CONFIANCE', 'quality_title' => 'La qualité dans<br><em>chaque détail.</em>', 'social_kicker' => 'INSPIRATION QUOTIDIENNE', 'social_title' => 'Suivez Nuttime<br><em>de plus près.</em>', 'instagram' => 'Ouvrir Instagram'],
    'final_cta' => ['kicker' => 'DÉCOUVREZ NUTTIME', 'title' => 'Un bon compagnon pour<br><em>chaque moment de la journée.</em>'],
    'product' => ['detail_label' => 'Sélection Nuttime', 'detail_copy' => 'Des ingrédients naturels, une production soignée et une expérience gourmande qui fait du bien.', 'whatsapp' => 'Demander par WhatsApp', 'image' => 'Image produit :number', 'breadcrumbs' => 'Fil d’Ariane produit', 'ingredients_kicker' => 'INFORMATIONS PRODUIT', 'ingredients' => 'Ingrédients', 'allergens' => 'Informations allergènes : ', 'nutrition_kicker' => 'VALEURS NUTRITIONNELLES', 'nutrition' => 'En un coup d’œil', 'packaging_kicker' => 'B2B / LOGISTIQUE', 'packaging' => 'Emballage et logistique', 'packaging_copy' => 'Les détails d’emballage pour la vente au détail et l’industrie sont structurés pour la planification des expéditions.'],
    'static' => ['about_kicker' => 'À PROPOS DE NUTTIME', 'about_title' => 'Qui <em>sommes-nous ?</em>', 'about_copy' => 'Notre entreprise est une petite entreprise familiale détenue et gérée par une famille de quatre personnes. Nous sommes partis de l’idée de nous efforcer de produire des aliments d’une qualité exceptionnelle. Nous développons tous nos produits pour qu’ils soient délicieux et nutritifs.', 'who_kicker' => 'QUI SOMMES-NOUS ?', 'who_title' => 'Une petite entreprise familiale.', 'who_copy_one' => 'Même si nous avons été multipliés par 400 en dix ans, nous nous sentons toujours comme une petite entreprise familiale.', 'who_copy_two' => 'Ce sentiment nous fait du bien.', 'mission_kicker' => 'NOTRE MISSION', 'mission_title' => 'Faire grandir le bon avec soin.', 'mission_copy_one' => 'Nous sommes fiers de contribuer à une société plus heureuse, plus saine, plus inclusive et plus sûre, tout en travaillant à devenir l’une des marques de pâtes de noisettes, d’amandes et de cacahuètes les plus savoureuses au monde.', 'mission_copy_two' => 'Nous traitons les ingrédients créés parfaitement par Allah et mis à notre disposition avec autant de simplicité, de soin et de délicatesse que possible.', 'mission_copy_three' => 'Nous respectons la terre, le ciel et tout ce qui se trouve entre les deux. En tant que fabricant alimentaire, nous avons conscience de notre responsabilité de créer un impact positif.', 'mission_donation_before' => 'Tous les bénéfices des produits achetés sur ce site sont consacrés en votre nom ; le revenu issu de notre travail est consacré au nom de notre fils bien-aimé', 'mission_donation_after' => 'aux orphelins et aux familles d’orphelins.', 'mission_quote' => '« Au jour des comptes, le poids d’un atome sera manifeste. »', 'company_kicker' => 'CONTACT / INFORMATIONS ENTREPRISE', 'company_title' => 'Nous sommes là.', 'phone_label' => 'TÉLÉPHONE', 'location_label' => 'LIEU', 'address_label' => 'ADRESSE', 'certificates_kicker' => 'FABRIQUÉ AVEC CONFIANCE', 'certificates_title' => 'Nos certificats<br><em>qualité.</em>', 'certificates_copy' => 'Consultez ici nos certificats à jour.', 'certificate' => 'CERTIFICAT', 'certificates_empty' => 'Nos certificats qualité seront bientôt disponibles ici.'],
    'contact' => ['kicker' => 'TRAVAILLONS ENSEMBLE', 'title' => 'Disons<br><em>bonjour.</em>', 'copy' => 'Contactez-nous pour nos produits, partenariats ou demandes de devis.', 'section' => 'CONTACT', 'name' => 'Nom complet', 'email' => 'E-mail', 'message' => 'Votre message', 'success' => 'Merci pour votre message. Notre équipe vous répondra rapidement.'],
    'factory' => ['kicker' => 'USINE / SITE DE PRODUCTION', 'fallback_name' => 'Notre site de production', 'address_label' => 'ADRESSE', 'phone_label' => 'TÉLÉPHONE', 'email_label' => 'E-MAIL', 'map_title' => 'Emplacement de l’usine Nuttime', 'map_copy' => 'Voir l’emplacement<br>sur Google Maps.'],
    'errors' => ['home' => 'Retour à l’accueil', 'products' => 'Voir les produits', '403' => ['heading' => 'Accès refusé', 'message' => 'Vous n’êtes pas autorisé à consulter cette page.'], '404' => ['heading' => 'Page introuvable', 'message' => 'La page recherchée n’existe pas ou a été déplacée.'], '419' => ['heading' => 'Session expirée', 'message' => 'Actualisez la page et réessayez.'], '500' => ['heading' => 'Une erreur est survenue', 'message' => 'Notre équipe technique a été informée. Réessayez dans quelques instants.']],
]);
