<?php

$site = require __DIR__.'/../tr/site.php';

return array_replace_recursive($site, [
    'language' => ['label' => 'Sprache', 'choose' => 'Sprache wählen'],
    'nav' => ['home' => 'Startseite', 'products' => 'Produkte', 'categories' => 'Kategorien', 'about' => 'Über uns', 'certificates' => 'Zertifikate', 'contact' => 'Kontakt', 'contents' => 'Geschichten'],
    'footer' => ['explore' => 'Entdecken', 'contact' => 'Kontakt', 'social' => 'Soziales', 'reach_us' => 'Kontakt aufnehmen', 'tagline' => 'Teile, was gut ist.', 'description' => 'Eine gute Idee aus der Natur. Gutes Gefühl bei jedem Bissen.'],
    'actions' => ['open_menu' => 'Menü öffnen oder schließen', 'view_product' => 'Produkt ansehen', 'all_products' => 'Alle Produkte', 'scroll_down' => 'Nach unten scrollen', 'discover' => 'Entdecken', 'discover_story' => 'Unsere Geschichte entdecken', 'open_document' => 'Dokument öffnen', 'view_document' => 'Dokument ansehen', 'contact_us' => 'Kontakt aufnehmen', 'get_directions' => 'Route planen', 'view_map' => 'Auf der Karte ansehen', 'send_message' => 'Nachricht senden', 'learn_more' => 'Mehr erfahren'],
    'catalog' => ['default_category' => 'Nuttime Auswahl', 'category' => 'Kategorie', 'products_count' => ':count Produkte', 'category_count' => 'KATEGORIE / :count PRODUKTE', 'empty' => 'Unsere Auswahl ist bald hier verfügbar.', 'category_empty' => 'In dieser Kategorie gibt es noch keine aktiven Produkte.'],
    'meta' => ['home' => ['title' => 'Nuttime', 'description' => 'Entdecken Sie intensive Nussaromen aus puren Zutaten mit Nuttime.'], 'products' => ['title' => 'Nuttime Produkte', 'description' => 'Entdecken Sie Nuttime Nusscremes und unsere sorgfältig zusammengestellte Auswahl.'], 'about' => ['title' => 'Über Nuttime', 'description' => 'Entdecken Sie Nuttime’s Produktionsansatz und Qualitätsfokus.'], 'certificates' => ['title' => 'Nuttime Zertifikate', 'description' => 'Entdecken Sie Nuttime Qualitätszertifikate und Produktionsstandards.'], 'contact' => ['title' => 'Nuttime Kontakt', 'description' => 'Kontaktieren Sie Nuttime für Partnerschaften und Produktanfragen.'], 'contents' => ['title' => 'Nuttime Geschichten', 'description' => 'Rezepte, Neuigkeiten und Geschichten aus der Nuttime Welt.']],
    'hero' => ['yer-fistigi-ezmesi' => ['eyebrow' => 'NUTTIME • 52% ERDNÜSSE', 'title' => 'ERDNUSS IN IHRER INTENSIVSTEN FORM'], 'findik-kremasi' => ['eyebrow' => 'NUTTIME • 45% HASELNÜSSE', 'title' => 'DER GERÖSTETE REICHTUM DER HASELNUSS'], 'antep-fistikli-kremasi' => ['eyebrow' => 'NUTTIME • 42% PISTAZIEN', 'title' => 'PISTAZIE IN IHRER INTENSIVSTEN FORM'], 'badem-unu' => ['eyebrow' => 'NUTTIME • 45% MANDELN', 'title' => 'DIE ELEGANTE, INTENSIVE TEXTUR DER MANDEL'], 'seker-ilavesiz-yer-fistigi-ezmesi' => ['eyebrow' => 'NUTTIME • OHNE ZUCKERZUSATZ • 72%', 'title' => 'PURER, INTENSIVER ERDNUSSGESCHMACK'], 'hindistan-cevizi-ezmesi' => ['eyebrow' => 'NUTTIME • 42% KOKOS', 'title' => 'EINE FRISCHE, CREMIGE TEXTUR']],
    'home' => ['banners_label' => 'Nuttime Auswahl', 'banner_one_kicker' => 'GENUSS DER NEUEN GENERATION', 'banner_one_title' => 'Pistazie<br>neu entdecken.', 'banner_two_kicker' => 'FÜR JEDEN TAG', 'banner_two_title' => 'Gutes Gefühl<br>mit jedem Löffel.', 'intro' => 'Wir machen aus besten Nüssen und puren Zutaten <em>den schönsten Moment Ihres Tages.</em>', 'featured_kicker' => 'SORGFÄLTIG AUSGEWÄHLT', 'featured_title' => 'Ausgewählte<br><em>Genüsse.</em>', 'categories_kicker' => 'KATEGORIEN', 'categories_title' => 'Finden, was sich<br><em>gut anfühlt.</em>', 'moment_kicker' => 'MEHR ALS EIN GLAS', 'moment_title' => 'Ein guter Begleiter für<br><em>jeden Geschmack und Rhythmus.</em>', 'story_kicker' => 'WER WIR SIND', 'story_title' => 'Gute Produkte,<br><em>gute Gefühle,</em><br>ein gutes Leben.', 'story_copy' => 'Nuttime bereitet den natürlichen Charakter sorgfältig ausgewählter Nüsse für Ihre tägliche Entdeckung zu.', 'quality_kicker' => 'MIT VERTRAUEN HERGESTELLT', 'quality_title' => 'Qualität in<br><em>jedem Detail.</em>', 'social_kicker' => 'TÄGLICHE INSPIRATION', 'social_title' => 'Nuttime<br><em>aus der Nähe erleben.</em>', 'instagram' => 'Instagram öffnen'],
    'final_cta' => ['kicker' => 'NUTTIME KENNENLERNEN', 'title' => 'Ein guter Begleiter für<br><em>jeden Moment des Tages.</em>'],
    'product' => ['detail_label' => 'Nuttime Auswahl', 'detail_copy' => 'Natürliche Zutaten, sorgfältige Herstellung und ein Geschmackserlebnis, das gut tut.', 'whatsapp' => 'Über WhatsApp fragen', 'related_kicker' => 'AUCH ENTDECKEN', 'related_title' => 'Weitere Genüsse<br><em>aus der Auswahl.</em>', 'image' => 'Produktbild :number'],
    'static' => ['about_kicker' => 'ÜBER NUTTIME', 'about_title' => 'Das Gute<br><em>ins Leben bringen.</em>', 'about_copy' => 'Der schlichte Ansatz hinter einer guten Idee aus der Natur.', 'about_lead' => 'Nuttime verbindet die besten Aromen der Natur mit dem Rhythmus des modernen Lebens.', 'approach_kicker' => 'EIN SCHLICHTER ANSATZ', 'approach_title' => 'Sorgfalt bei der Auswahl,<br><em>Sorgfalt bei der Herstellung.</em>', 'approach_copy' => 'Für uns entsteht guter Geschmack aus guten Zutaten, dem richtigen Prozess und einem ehrlichen Ansatz.', 'meet_us' => 'Uns kennenlernen', 'certificates_kicker' => 'MIT VERTRAUEN HERGESTELLT', 'certificates_title' => 'Unsere Qualitäts-<br><em>zertifikate.</em>', 'certificates_copy' => 'Hier können Sie unsere aktuellen Zertifikate einsehen.', 'certificate' => 'ZERTIFIKAT', 'certificates_empty' => 'Unsere Qualitätszertifikate werden bald hier verfügbar sein.'],
    'contact' => ['kicker' => 'LASSEN SIE UNS ZUSAMMENARBEITEN', 'title' => 'Sagen wir<br><em>Hallo.</em>', 'copy' => 'Kontaktieren Sie uns für Produkte, Partnerschaften oder Angebotsanfragen.', 'section' => 'KONTAKT', 'name' => 'Vollständiger Name', 'email' => 'E-Mail', 'message' => 'Ihre Nachricht', 'success' => 'Vielen Dank für Ihre Nachricht. Unser Team meldet sich in Kürze bei Ihnen.'],
    'factory' => ['kicker' => 'FABRIK / PRODUKTIONSSTÄTTE', 'fallback_name' => 'Unsere Produktionsstätte', 'address_label' => 'ADRESSE', 'phone_label' => 'TELEFON', 'email_label' => 'E-MAIL', 'map_title' => 'Nuttime Fabrikstandort', 'map_copy' => 'Standort auf<br>Google Maps ansehen.'],
    'errors' => ['home' => 'Zur Startseite', 'products' => 'Produkte ansehen', '403' => ['heading' => 'Zugriff verweigert', 'message' => 'Sie haben keine Berechtigung, diese Seite anzuzeigen.'], '404' => ['heading' => 'Seite nicht gefunden', 'message' => 'Die gesuchte Seite existiert nicht oder wurde verschoben.'], '419' => ['heading' => 'Sitzung abgelaufen', 'message' => 'Bitte aktualisieren Sie die Seite und versuchen Sie es erneut.'], '500' => ['heading' => 'Ein Fehler ist aufgetreten', 'message' => 'Unser technisches Team wurde informiert. Bitte versuchen Sie es in Kürze erneut.']],
]);
