<?php

$site = require __DIR__.'/../tr/site.php';

return array_replace_recursive($site, [
    'language' => ['label' => 'Sprache', 'choose' => 'Sprache wählen'],
    'nav' => ['home' => 'Startseite', 'products' => 'Produkte', 'categories' => 'Kategorien', 'about' => 'Über uns', 'certificates' => 'Zertifikate', 'contact' => 'Kontakt', 'contents' => 'Geschichten'],
    'footer' => ['explore' => 'Entdecken', 'contact' => 'Kontakt', 'social' => 'Soziales', 'reach_us' => 'Kontakt aufnehmen', 'tagline' => 'Teile, was gut ist.', 'description' => 'Eine gute Idee aus der Natur. Gutes Gefühl bei jedem Bissen.'],
    'actions' => ['open_menu' => 'Menü öffnen oder schließen', 'view_product' => 'Produkt ansehen', 'all_products' => 'Alle Produkte', 'scroll_down' => 'Nach unten scrollen', 'discover' => 'Entdecken', 'discover_story' => 'Unsere Geschichte entdecken', 'open_document' => 'Dokument öffnen', 'view_document' => 'Dokument ansehen', 'contact_us' => 'Kontakt aufnehmen', 'get_directions' => 'Route planen', 'view_map' => 'Auf der Karte ansehen', 'send_message' => 'Nachricht senden', 'learn_more' => 'Mehr erfahren', 'close' => 'Schließen'],
    'catalog' => ['default_category' => 'Nuttime Auswahl', 'category' => 'Kategorie', 'products_count' => ':count Produkte', 'category_count' => 'KATEGORIE / :count PRODUKTE', 'empty' => 'Unsere Auswahl ist bald hier verfügbar.', 'category_empty' => 'In dieser Kategorie gibt es noch keine aktiven Produkte.'],
    'meta' => ['home' => ['title' => 'Nuttime', 'description' => 'Entdecken Sie intensive Nussaromen aus puren Zutaten mit Nuttime.'], 'products' => ['title' => 'Nuttime Produkte', 'description' => 'Entdecken Sie Nuttime Nusscremes und unsere sorgfältig zusammengestellte Auswahl.'], 'about' => ['title' => 'Über Nuttime', 'description' => 'Entdecken Sie Nuttime’s Produktionsansatz und Qualitätsfokus.'], 'certificates' => ['title' => 'Nuttime Zertifikate', 'description' => 'Entdecken Sie Nuttime Qualitätszertifikate und Produktionsstandards.'], 'contact' => ['title' => 'Nuttime Kontakt', 'description' => 'Kontaktieren Sie Nuttime für Partnerschaften und Produktanfragen.'], 'contents' => ['title' => 'Nuttime Geschichten', 'description' => 'Rezepte, Neuigkeiten und Geschichten aus der Nuttime Welt.']],
    'hero' => ['yer-fistigi-ezmesi' => ['eyebrow' => 'NUTTIME • 52% ERDNÜSSE', 'title' => 'ERDNUSS IN IHRER INTENSIVSTEN FORM'], 'findik-kremasi' => ['eyebrow' => 'NUTTIME • 45% HASELNÜSSE', 'title' => 'DER GERÖSTETE REICHTUM DER HASELNUSS'], 'antep-fistikli-kremasi' => ['eyebrow' => 'NUTTIME • 42% PISTAZIEN', 'title' => 'PISTAZIE IN IHRER INTENSIVSTEN FORM'], 'badem-unu' => ['eyebrow' => 'NUTTIME • 45% MANDELN', 'title' => 'DIE ELEGANTE, INTENSIVE TEXTUR DER MANDEL'], 'seker-ilavesiz-yer-fistigi-ezmesi' => ['eyebrow' => 'NUTTIME • OHNE ZUCKERZUSATZ • 72%', 'title' => 'PURER, INTENSIVER ERDNUSSGESCHMACK'], 'hindistan-cevizi-ezmesi' => ['eyebrow' => 'NUTTIME • 42% KOKOS', 'title' => 'EINE FRISCHE, CREMIGE TEXTUR']],
    'home' => ['banners_label' => 'Nuttime Auswahl', 'banner_one_kicker' => 'GENUSS DER NEUEN GENERATION', 'banner_one_title' => 'Pistazie<br>neu entdecken.', 'banner_two_kicker' => 'FÜR JEDEN TAG', 'banner_two_title' => 'Gutes Gefühl<br>mit jedem Löffel.', 'intro' => 'Wir machen aus besten Nüssen und puren Zutaten <em>den schönsten Moment Ihres Tages.</em>', 'featured_kicker' => 'SORGFÄLTIG AUSGEWÄHLT', 'featured_title' => 'Ausgewählte<br><em>Genüsse.</em>', 'categories_kicker' => 'KATEGORIEN', 'categories_title' => 'Finden, was sich<br><em>gut anfühlt.</em>', 'moment_kicker' => 'MEHR ALS EIN GLAS', 'moment_title' => 'Ein guter Begleiter für<br><em>jeden Geschmack und Rhythmus.</em>', 'story_kicker' => 'WER WIR SIND', 'story_title' => 'Gute Produkte,<br><em>gute Gefühle,</em><br>ein gutes Leben.', 'story_copy' => 'Nuttime bereitet den natürlichen Charakter sorgfältig ausgewählter Nüsse für Ihre tägliche Entdeckung zu.', 'quality_kicker' => 'MIT VERTRAUEN HERGESTELLT', 'quality_title' => 'Qualität in<br><em>jedem Detail.</em>', 'social_kicker' => 'TÄGLICHE INSPIRATION', 'social_title' => 'Nuttime<br><em>aus der Nähe erleben.</em>', 'instagram' => 'Instagram öffnen'],
    'final_cta' => ['kicker' => 'NUTTIME KENNENLERNEN', 'title' => 'Ein guter Begleiter für<br><em>jeden Moment des Tages.</em>'],
    'product' => ['detail_label' => 'Nuttime Auswahl', 'detail_copy' => 'Natürliche Zutaten, sorgfältige Herstellung und ein Geschmackserlebnis, das gut tut.', 'whatsapp' => 'Über WhatsApp fragen', 'related_kicker' => 'AUCH ENTDECKEN', 'related_title' => 'Weitere Genüsse<br><em>aus der Auswahl.</em>', 'image' => 'Produktbild :number', 'breadcrumbs' => 'Produktpfad', 'ingredients_kicker' => 'PRODUKTINFORMATION', 'ingredients' => 'Zutaten', 'allergens' => 'Allergenhinweis: ', 'nutrition_kicker' => 'NÄHRWERTE', 'nutrition' => 'Auf einen Blick', 'packaging_kicker' => 'B2B / LOGISTIK', 'packaging' => 'Verpackung & Logistik', 'packaging_copy' => 'Informationen zu Einzelhandel und Industriegebinden sind für die Versandplanung strukturiert.', 'nutrition_fields' => ['energy' => 'Energie (kJ/kcal)', 'fat' => 'Fett (%)', 'saturated_fat' => 'Gesättigte Fettsäuren (g)', 'trans_fat' => 'Transfett (g)', 'carbohydrates' => 'Kohlenhydrate (g)', 'sugar' => 'Zucker (g)', 'fibre' => 'Ballaststoffe (g)', 'protein' => 'Protein (g)', 'salt' => 'Salz (g)'], 'packaging_groups' => ['general' => 'Verpackung', 'jar' => 'Glas', 'carton' => 'Karton', 'pallet' => 'Kartonpalette', 'industrial' => 'Industrieeimer / Europalette', 'dimensions' => 'Technische Maße'], 'packaging_fields' => ['net_weight' => 'Nettogewicht', 'gross_weight' => 'Bruttogewicht', 'diameter' => 'Durchmesser', 'height' => 'Höhe', 'units' => 'Einheiten pro Karton', 'buckets_on_pallet' => 'Eimer pro Palette', 'dimensions' => 'Maße', 'dimensions_inches' => 'Zollangabe', 'cartons' => 'Kartons pro Palette', 'type' => 'Palettentyp', 'loaded_height' => 'Beladene Palettenhöhe', 'loaded_height_inches' => 'Zollangabe', 'd1' => 'D1', 'd2' => 'D2', 'd3' => 'D3', 'h' => 'H']],
    'static' => ['about_kicker' => 'ÜBER NUTTIME', 'about_title' => 'Wer <em>sind wir?</em>', 'about_copy' => 'Unser Unternehmen ist ein kleines Familienunternehmen, das einer vierköpfigen Familie gehört und von ihr geführt wird. Wir sind mit dem Gedanken gestartet, Lebensmittel von höchster Qualität herzustellen. Alle unsere Produkte entwickeln wir so, dass sie köstlich und nahrhaft sind.', 'about_lead' => 'Wir glauben, dass Ernährung die Grundlage der Gesundheit ist.', 'who_kicker' => 'WER WIR SIND', 'who_title' => 'Ein kleines Familienunternehmen.', 'who_copy_one' => 'Obwohl wir auf dem Weg, den wir mit diesem Glauben begonnen haben, in 10 Jahren um das 400-Fache gewachsen sind, fühlen wir uns noch immer wie ein kleines Familienunternehmen.', 'who_copy_two' => 'Dieses Gefühl tut uns gut.', 'mission_kicker' => 'UNSERE MISSION', 'mission_title' => 'Das Gute mit Sorgfalt wachsen lassen.', 'mission_copy_one' => 'Wir sind stolz darauf, ein wichtiger Teil der Lösung auf dem Weg zu einer glücklicheren, gesünderen, inklusiveren und sichereren Gesellschaft für alle zu sein und mit dem Ziel zu arbeiten, eine der köstlichsten Haselnuss-, Mandel- und Erdnusscrememarken der Welt zu werden.', 'mission_copy_two' => 'Wir behandeln die Zutaten, die Allah vollkommen geschaffen und uns dargeboten hat, so einfach, sorgfältig und behutsam wie möglich.', 'mission_copy_three' => 'Wir respektieren die Erde, den Himmel und alles dazwischen. Als Lebensmittelhersteller sind wir uns unserer Verantwortung bewusst, uns um eine positive Wirkung zu bemühen.', 'mission_donation_before' => 'Der gesamte Gewinn aus den Produkten, die Sie über diese Website kaufen, wird in Ihrem Namen gespendet; die Einnahmen aus der Arbeit werden im Namen unseres geliebten Sohnes', 'mission_donation_name' => 'Oğuzhan Kuş', 'mission_donation_after' => 'Waisen und Waisenfamilien gewidmet.', 'mission_quote' => '„Am Tag der Abrechnung wird selbst das Gewicht eines Staubkorns offenbar werden.“', 'company_kicker' => 'KONTAKT / FIRMENINFORMATIONEN', 'company_title' => 'Wir sind da.', 'phone_label' => 'TELEFON', 'location_label' => 'STANDORT', 'address_label' => 'ADRESSE', 'certificates_kicker' => 'MIT VERTRAUEN HERGESTELLT', 'certificates_title' => 'Unsere Qualitäts-<br><em>zertifikate.</em>', 'certificates_copy' => 'Hier können Sie unsere aktuellen Zertifikate einsehen.', 'certificate' => 'ZERTIFIKAT', 'certificates_empty' => 'Unsere Qualitätszertifikate werden bald hier verfügbar sein.'],
    'contact' => ['kicker' => 'LASSEN SIE UNS ZUSAMMENARBEITEN', 'title' => 'Sagen wir<br><em>Hallo.</em>', 'copy' => 'Kontaktieren Sie uns für Produkte, Partnerschaften oder Angebotsanfragen.', 'section' => 'KONTAKT', 'name' => 'Vollständiger Name', 'email' => 'E-Mail', 'message' => 'Ihre Nachricht', 'success' => 'Vielen Dank für Ihre Nachricht. Unser Team meldet sich in Kürze bei Ihnen.'],
    'factory' => ['kicker' => 'FABRIK / PRODUKTIONSSTÄTTE', 'fallback_name' => 'Unsere Produktionsstätte', 'address_label' => 'ADRESSE', 'phone_label' => 'TELEFON', 'email_label' => 'E-MAIL', 'map_title' => 'Nuttime Fabrikstandort', 'map_copy' => 'Standort auf<br>Google Maps ansehen.'],
    'errors' => ['home' => 'Zur Startseite', 'products' => 'Produkte ansehen', '403' => ['heading' => 'Zugriff verweigert', 'message' => 'Sie haben keine Berechtigung, diese Seite anzuzeigen.'], '404' => ['heading' => 'Seite nicht gefunden', 'message' => 'Die gesuchte Seite existiert nicht oder wurde verschoben.'], '419' => ['heading' => 'Sitzung abgelaufen', 'message' => 'Bitte aktualisieren Sie die Seite und versuchen Sie es erneut.'], '500' => ['heading' => 'Ein Fehler ist aufgetreten', 'message' => 'Unser technisches Team wurde informiert. Bitte versuchen Sie es in Kürze erneut.']],
]);
