<?php

$site = require __DIR__.'/../en/site.php';

return array_replace_recursive($site, [
    'language' => ['label' => 'Lingua', 'choose' => 'Scegli lingua'],
    'nav' => ['home' => 'Home', 'products' => 'Prodotti', 'categories' => 'Categorie', 'about' => 'Chi siamo', 'certificates' => 'Certificati', 'contact' => 'Contatti', 'contents' => 'Storie'],
    'footer' => ['explore' => 'Esplora', 'contact' => 'Contatti', 'social' => 'Social', 'reach_us' => 'Contattaci', 'tagline' => 'Condividi ciò che è buono.', 'description' => 'Una buona idea dalla natura. Stai bene a ogni assaggio.'],
    'actions' => ['open_menu' => 'Apri o chiudi menu', 'view_product' => 'Vedi prodotto', 'all_products' => 'Tutti i prodotti', 'scroll_down' => 'Scorri in basso', 'discover' => 'Scopri', 'discover_story' => 'Scopri la nostra storia', 'open_document' => 'Apri documento', 'view_document' => 'Vedi documento', 'contact_us' => 'Contattaci', 'get_directions' => 'Indicazioni', 'view_map' => 'Vedi sulla mappa', 'send_message' => 'Invia messaggio', 'learn_more' => 'Scopri', 'close' => 'Chiudi'],
    'catalog' => ['default_category' => 'Selezione Nuttime', 'category' => 'categoria', 'products_count' => ':count prodotti', 'category_count' => 'CATEGORIA / :count PRODOTTI', 'empty' => 'La nostra selezione arriverà presto.', 'category_empty' => 'Non ci sono ancora prodotti attivi in questa categoria.'],
    'home' => ['banners_label' => 'Selezioni Nuttime', 'banner_one_kicker' => 'UNA NUOVA GENERAZIONE DI GUSTO', 'banner_one_title' => 'Riscopri<br>il pistacchio.', 'banner_two_kicker' => 'PER OGNI GIORNO', 'banner_two_title' => 'Stai bene<br>in un cucchiaio.', 'intro' => 'Trasformiamo ottima frutta secca e ingredienti semplici nel <em>momento più piacevole della tua giornata.</em>', 'featured_kicker' => 'SCELTI CON CURA', 'featured_title' => 'Sapori<br><em>in evidenza.</em>', 'categories_kicker' => 'CATEGORIE', 'categories_title' => 'Trova ciò che ti fa<br><em>stare bene.</em>', 'story_kicker' => 'CHI SIAMO', 'story_title' => 'Buoni prodotti,<br><em>buone sensazioni,</em><br>una buona vita.', 'story_copy' => 'Nuttime prepara il carattere naturale della frutta secca selezionata con cura, da riscoprire ogni giorno.', 'quality_kicker' => 'PRODOTTO CON FIDUCIA', 'quality_title' => 'Qualità in<br><em>ogni dettaglio.</em>', 'social_kicker' => 'ISPIRAZIONE QUOTIDIANA', 'social_title' => 'Segui Nuttime<br><em>più da vicino.</em>', 'instagram' => 'Apri Instagram'],
    'final_cta' => ['kicker' => 'CONOSCI NUTTIME', 'title' => 'Un buon compagno per<br><em>ogni momento della giornata.</em>'],
    'product' => ['detail_label' => 'Selezione Nuttime', 'detail_copy' => 'Ingredienti naturali, produzione attenta e un’esperienza di gusto che fa stare bene.', 'whatsapp' => 'Chiedi su WhatsApp', 'image' => 'Immagine prodotto :number', 'breadcrumbs' => 'Percorso prodotto', 'ingredients_kicker' => 'INFORMAZIONI SUL PRODOTTO', 'ingredients' => 'Ingredienti', 'allergens' => 'Informazioni sugli allergeni: ', 'nutrition_kicker' => 'VALORI NUTRIZIONALI', 'nutrition' => 'A colpo d’occhio', 'packaging_kicker' => 'B2B / LOGISTICA', 'packaging' => 'Confezione e logistica', 'packaging_copy' => 'I dettagli di confezione per vendita al dettaglio e industria sono organizzati per la pianificazione delle spedizioni.'],
    'static' => ['about_kicker' => 'SU NUTTIME', 'about_title' => 'Chi <em>siamo?</em>', 'about_copy' => 'La nostra azienda è una piccola impresa familiare di proprietà e gestione di una famiglia di quattro persone. Siamo partiti dall’idea di impegnarci per produrre alimenti di qualità eccellente. Sviluppiamo ogni prodotto per renderlo gustoso e nutriente.', 'who_kicker' => 'CHI SIAMO', 'who_title' => 'Una piccola impresa familiare.', 'who_copy_one' => 'Anche se in dieci anni siamo cresciuti di 400 volte, ci sentiamo ancora una piccola impresa familiare.', 'who_copy_two' => 'Questa sensazione ci fa stare bene.', 'mission_kicker' => 'LA NOSTRA MISSIONE', 'mission_title' => 'Coltivare il buono con cura.', 'mission_copy_one' => 'Siamo orgogliosi di essere una parte importante della soluzione verso una società più felice, sana, inclusiva e sicura, lavorando per diventare uno dei marchi di creme di nocciole, mandorle e arachidi più gustosi al mondo.', 'mission_copy_two' => 'Trattiamo gli ingredienti creati perfettamente da Allah e messi a nostra disposizione nel modo più semplice, attento e delicato possibile.', 'mission_copy_three' => 'Rispettiamo la terra, il cielo e tutto ciò che sta nel mezzo. Come produttori alimentari, siamo consapevoli della responsabilità di creare un impatto positivo.', 'mission_donation_before' => 'Tutti i profitti dei prodotti acquistati tramite questo sito sono destinati a tuo nome; il ricavato del nostro lavoro è dedicato, a nome del nostro amato figlio', 'mission_donation_after' => 'a orfani e famiglie di orfani.', 'mission_quote' => '«Nel giorno del rendiconto, anche il peso di un atomo sarà manifesto».', 'company_kicker' => 'CONTATTI / INFORMAZIONI AZIENDALI', 'company_title' => 'Siamo qui.', 'phone_label' => 'TELEFONO', 'location_label' => 'LOCALITÀ', 'address_label' => 'INDIRIZZO', 'certificates_kicker' => 'PRODOTTO CON FIDUCIA', 'certificates_title' => 'I nostri certificati<br><em>di qualità.</em>', 'certificates_copy' => 'Consulta qui i nostri certificati aggiornati.', 'certificate' => 'CERTIFICATO', 'certificates_empty' => 'I nostri certificati di qualità saranno presto disponibili qui.'],
    'contact' => ['kicker' => 'LAVORIAMO INSIEME', 'title' => 'Diciamo<br><em>ciao.</em>', 'copy' => 'Contattaci per prodotti, collaborazioni o richieste di preventivo.', 'section' => 'CONTATTI', 'name' => 'Nome completo', 'email' => 'E-mail', 'message' => 'Il tuo messaggio', 'success' => 'Grazie per il messaggio. Il nostro team ti risponderà presto.'],
    'factory' => ['kicker' => 'FABBRICA / STABILIMENTO PRODUTTIVO', 'fallback_name' => 'Il nostro stabilimento produttivo', 'address_label' => 'INDIRIZZO', 'phone_label' => 'TELEFONO', 'email_label' => 'E-MAIL', 'map_title' => 'Posizione fabbrica Nuttime', 'map_copy' => 'Vedi la posizione<br>su Google Maps.'],
    'errors' => ['home' => 'Torna alla home', 'products' => 'Vedi prodotti', '403' => ['heading' => 'Accesso negato', 'message' => 'Non hai l’autorizzazione per vedere questa pagina.'], '404' => ['heading' => 'Pagina non trovata', 'message' => 'La pagina cercata non esiste o potrebbe essere stata spostata.'], '419' => ['heading' => 'Sessione scaduta', 'message' => 'Aggiorna la pagina e riprova.'], '500' => ['heading' => 'Si è verificato un problema', 'message' => 'Il nostro team tecnico è stato informato. Riprova tra poco.']],
]);
