<?php

$site = require __DIR__.'/../en/site.php';

return array_replace_recursive($site, [
    'language' => ['label' => 'Idioma', 'choose' => 'Elegir idioma'],
    'nav' => ['home' => 'Inicio', 'products' => 'Productos', 'categories' => 'Categorías', 'about' => 'Nosotros', 'certificates' => 'Certificados', 'contact' => 'Contacto', 'contents' => 'Historias'],
    'footer' => ['explore' => 'Explorar', 'contact' => 'Contacto', 'social' => 'Redes sociales', 'reach_us' => 'Contáctanos', 'tagline' => 'Comparte lo bueno.', 'description' => 'Una buena idea de la naturaleza. Siéntete bien en cada bocado.'],
    'actions' => ['open_menu' => 'Abrir o cerrar menú', 'view_product' => 'Ver producto', 'all_products' => 'Todos los productos', 'scroll_down' => 'Desplazar hacia abajo', 'discover' => 'Descubrir', 'discover_story' => 'Descubre nuestra historia', 'open_document' => 'Abrir documento', 'view_document' => 'Ver documento', 'contact_us' => 'Contáctanos', 'get_directions' => 'Cómo llegar', 'view_map' => 'Ver en el mapa', 'send_message' => 'Enviar mensaje', 'learn_more' => 'Descubrir', 'close' => 'Cerrar'],
    'catalog' => ['default_category' => 'Selección Nuttime', 'category' => 'categoría', 'products_count' => ':count productos', 'category_count' => 'CATEGORÍA / :count PRODUCTOS', 'empty' => 'Nuestra selección estará aquí pronto.', 'category_empty' => 'Aún no hay productos activos en esta categoría.'],
    'meta' => ['home' => ['title' => 'Nuttime', 'description' => 'Descubre con Nuttime intensos sabores de frutos secos elaborados con ingredientes sencillos.'], 'products' => ['title' => 'Productos Nuttime', 'description' => 'Descubre las cremas de frutos secos Nuttime y nuestra selección elaborada con cuidado.'], 'about' => ['title' => 'Sobre Nuttime', 'description' => 'Descubre el enfoque de Nuttime sobre producción y calidad.'], 'certificates' => ['title' => 'Certificados Nuttime', 'description' => 'Consulta los certificados de calidad y estándares de producción de Nuttime.'], 'contact' => ['title' => 'Contacto Nuttime', 'description' => 'Contacta con Nuttime para colaboraciones y consultas de productos.']],
    'home' => ['banners_label' => 'Selecciones Nuttime', 'banner_one_kicker' => 'UNA NUEVA GENERACIÓN DE SABOR', 'banner_one_title' => 'Redescubre<br>el pistacho.', 'banner_two_kicker' => 'PARA CADA DÍA', 'banner_two_title' => 'Siéntete bien<br>en una cucharada.', 'intro' => 'Convertimos buenos frutos secos e ingredientes sencillos en <em>el momento más agradable de tu día.</em>', 'featured_kicker' => 'SELECCIONADO CON CUIDADO', 'featured_title' => 'Sabores<br><em>destacados.</em>', 'categories_kicker' => 'CATEGORÍAS', 'categories_title' => 'Encuentra lo que te<br><em>hace sentir bien.</em>', 'story_kicker' => 'QUIÉNES SOMOS', 'story_title' => 'Buenos productos,<br><em>buenas sensaciones,</em><br>una buena vida.', 'story_copy' => 'Nuttime prepara el carácter natural de frutos secos seleccionados para que lo redescubras cada día.', 'quality_kicker' => 'ELABORADO CON CONFIANZA', 'quality_title' => 'Calidad en<br><em>cada detalle.</em>', 'social_kicker' => 'INSPIRACIÓN DIARIA', 'social_title' => 'Sigue a Nuttime<br><em>más de cerca.</em>', 'instagram' => 'Abrir Instagram'],
    'final_cta' => ['kicker' => 'CONOCE NUTTIME', 'title' => 'Un buen acompañante para<br><em>cada momento del día.</em>'],
    'product' => ['detail_label' => 'Selección Nuttime', 'detail_copy' => 'Ingredientes naturales, producción cuidadosa y una experiencia de sabor que te hace sentir bien.', 'whatsapp' => 'Consultar por WhatsApp', 'image' => 'Imagen del producto :number', 'breadcrumbs' => 'Ruta del producto', 'ingredients_kicker' => 'INFORMACIÓN DEL PRODUCTO', 'ingredients' => 'Ingredientes', 'allergens' => 'Información de alérgenos: ', 'nutrition_kicker' => 'VALORES NUTRICIONALES', 'nutrition' => 'De un vistazo', 'packaging_kicker' => 'B2B / LOGÍSTICA', 'packaging' => 'Envase y logística', 'packaging_copy' => 'Los detalles de envase comercial e industrial se presentan de forma estructurada para la planificación de envíos.'],
    'static' => ['about_kicker' => 'SOBRE NUTTIME', 'about_title' => '¿Quiénes <em>somos?</em>', 'about_copy' => 'Somos una pequeña empresa familiar propiedad y gestión de una familia de cuatro personas. Comenzamos con la idea de esforzarnos por producir alimentos de una calidad excepcional. Desarrollamos todos nuestros productos para que sean deliciosos y nutritivos.', 'who_kicker' => 'QUIÉNES SOMOS', 'who_title' => 'Una pequeña empresa familiar.', 'who_copy_one' => 'Aunque hemos crecido 400 veces en 10 años, seguimos sintiéndonos una pequeña empresa familiar.', 'who_copy_two' => 'Esa sensación nos hace bien.', 'mission_kicker' => 'NUESTRA MISIÓN', 'mission_title' => 'Cultivar lo bueno con cuidado.', 'mission_copy_one' => 'Estamos orgullosos de ser una parte importante de la solución para una sociedad más feliz, saludable, inclusiva y segura, mientras trabajamos para ser una de las marcas de cremas de avellana, almendra y cacahuete más deliciosas del mundo.', 'mission_copy_two' => 'Tratamos los ingredientes que Alá creó de forma perfecta y puso a nuestra disposición de la manera más sencilla, cuidadosa y delicada posible.', 'mission_copy_three' => 'Respetamos la tierra, el cielo y todo lo que hay entre ambos. Como fabricante de alimentos, somos conscientes de nuestra responsabilidad de lograr un impacto positivo.', 'mission_donation_before' => 'Todos los beneficios de los productos adquiridos en este sitio se destinan en tu nombre; los ingresos de nuestro trabajo se destinan, en nombre de nuestro querido hijo', 'mission_donation_after' => 'a huérfanos y familias de huérfanos.', 'mission_quote' => '«En el día de la rendición de cuentas, hasta el peso de un átomo quedará manifiesto».', 'company_kicker' => 'CONTACTO / INFORMACIÓN DE LA EMPRESA', 'company_title' => 'Estamos aquí.', 'phone_label' => 'TELÉFONO', 'location_label' => 'UBICACIÓN', 'address_label' => 'DIRECCIÓN', 'certificates_kicker' => 'ELABORADO CON CONFIANZA', 'certificates_title' => 'Nuestros certificados<br><em>de calidad.</em>', 'certificates_copy' => 'Consulta aquí nuestros certificados vigentes.', 'certificate' => 'CERTIFICADO', 'certificates_empty' => 'Nuestros certificados de calidad estarán disponibles aquí pronto.'],
    'contact' => ['kicker' => 'TRABAJEMOS JUNTOS', 'title' => 'Digamos<br><em>hola.</em>', 'copy' => 'Contáctanos para productos, colaboraciones o solicitudes de presupuesto.', 'section' => 'CONTACTO', 'name' => 'Nombre completo', 'email' => 'Correo electrónico', 'message' => 'Tu mensaje', 'success' => 'Gracias por tu mensaje. Nuestro equipo te responderá en breve.'],
    'factory' => ['kicker' => 'FÁBRICA / INSTALACIÓN DE PRODUCCIÓN', 'fallback_name' => 'Nuestra instalación de producción', 'address_label' => 'DIRECCIÓN', 'phone_label' => 'TELÉFONO', 'email_label' => 'CORREO', 'map_title' => 'Ubicación de la fábrica Nuttime', 'map_copy' => 'Ver la ubicación<br>en Google Maps.'],
    'errors' => ['home' => 'Volver al inicio', 'products' => 'Ver productos', '403' => ['heading' => 'Acceso denegado', 'message' => 'No tienes permiso para ver esta página.'], '404' => ['heading' => 'Página no encontrada', 'message' => 'La página que buscas no existe o se ha movido.'], '419' => ['heading' => 'Sesión caducada', 'message' => 'Actualiza la página e inténtalo de nuevo.'], '500' => ['heading' => 'Algo salió mal', 'message' => 'Nuestro equipo técnico ha sido informado. Inténtalo de nuevo en breve.']],
]);
