<?php

$site = require __DIR__.'/../en/site.php';

return array_replace_recursive($site, [
    'language' => ['label' => 'Idioma', 'choose' => 'Escolher idioma'],
    'nav' => ['home' => 'Início', 'products' => 'Produtos', 'categories' => 'Categorias', 'about' => 'Sobre nós', 'certificates' => 'Certificados', 'contact' => 'Contacto', 'contents' => 'Histórias'],
    'footer' => ['explore' => 'Explorar', 'contact' => 'Contacto', 'social' => 'Redes sociais', 'reach_us' => 'Fale connosco', 'tagline' => 'Partilhe o que é bom.', 'description' => 'Uma boa ideia vinda da natureza. Sinta-se bem em cada sabor.'],
    'actions' => ['open_menu' => 'Abrir ou fechar menu', 'view_product' => 'Ver produto', 'all_products' => 'Todos os produtos', 'scroll_down' => 'Descer', 'discover' => 'Descobrir', 'discover_story' => 'Descubra a nossa história', 'open_document' => 'Abrir documento', 'view_document' => 'Ver documento', 'contact_us' => 'Contacte-nos', 'get_directions' => 'Obter direções', 'view_map' => 'Ver no mapa', 'send_message' => 'Enviar mensagem', 'learn_more' => 'Descobrir', 'close' => 'Fechar'],
    'catalog' => ['default_category' => 'Seleção Nuttime', 'category' => 'categoria', 'products_count' => ':count produtos', 'category_count' => 'CATEGORIA / :count PRODUTOS', 'empty' => 'A nossa seleção estará aqui em breve.', 'category_empty' => 'Ainda não existem produtos ativos nesta categoria.'],
    'home' => ['banners_label' => 'Seleções Nuttime', 'banner_one_kicker' => 'UMA NOVA GERAÇÃO DE SABOR', 'banner_one_title' => 'Redescubra<br>o pistácio.', 'banner_two_kicker' => 'PARA TODOS OS DIAS', 'banner_two_title' => 'Sinta-se bem<br>numa colher.', 'intro' => 'Transformamos bons frutos secos e ingredientes simples no <em>momento mais agradável do seu dia.</em>', 'featured_kicker' => 'SELECIONADOS COM CUIDADO', 'featured_title' => 'Sabores<br><em>em destaque.</em>', 'categories_kicker' => 'CATEGORIAS', 'categories_title' => 'Encontre o que lhe faz<br><em>bem.</em>', 'story_kicker' => 'QUEM SOMOS', 'story_title' => 'Bons produtos,<br><em>boas sensações,</em><br>uma boa vida.', 'story_copy' => 'Nuttime prepara o carácter natural de frutos secos cuidadosamente selecionados para redescobrir todos os dias.', 'quality_kicker' => 'FEITO COM CONFIANÇA', 'quality_title' => 'Qualidade em<br><em>cada detalhe.</em>', 'social_kicker' => 'INSPIRAÇÃO DIÁRIA', 'social_title' => 'Siga a Nuttime<br><em>mais de perto.</em>', 'instagram' => 'Abrir Instagram'],
    'final_cta' => ['kicker' => 'CONHEÇA A NUTTIME', 'title' => 'Uma boa companhia para<br><em>todos os momentos do dia.</em>'],
    'product' => ['detail_label' => 'Seleção Nuttime', 'detail_copy' => 'Ingredientes naturais, produção cuidada e uma experiência de sabor que sabe bem.', 'whatsapp' => 'Perguntar pelo WhatsApp', 'image' => 'Imagem do produto :number', 'breadcrumbs' => 'Percurso do produto', 'ingredients_kicker' => 'INFORMAÇÃO DO PRODUTO', 'ingredients' => 'Ingredientes', 'allergens' => 'Informação sobre alergénios: ', 'nutrition_kicker' => 'VALORES NUTRICIONAIS', 'nutrition' => 'Num relance', 'packaging_kicker' => 'B2B / LOGÍSTICA', 'packaging' => 'Embalagem e logística', 'packaging_copy' => 'Os detalhes de embalagem para retalho e indústria são organizados para o planeamento de expedições.'],
    'static' => ['about_kicker' => 'SOBRE A NUTTIME', 'about_title' => 'Quem <em>somos?</em>', 'about_copy' => 'A nossa empresa é um pequeno negócio familiar, detido e gerido por uma família de quatro pessoas. Começámos com a ideia de nos esforçarmos por produzir alimentos de qualidade superior. Desenvolvemos todos os nossos produtos para serem deliciosos e nutritivos.', 'who_kicker' => 'QUEM SOMOS', 'who_title' => 'Um pequeno negócio familiar.', 'who_copy_one' => 'Apesar de termos crescido 400 vezes em 10 anos, continuamos a sentir-nos como um pequeno negócio familiar.', 'who_copy_two' => 'Essa sensação faz-nos bem.', 'mission_kicker' => 'A NOSSA MISSÃO', 'mission_title' => 'Fazer crescer o que é bom com cuidado.', 'mission_copy_one' => 'Orgulhamo-nos de ser uma parte importante da solução para uma sociedade mais feliz, saudável, inclusiva e segura, trabalhando para nos tornarmos uma das mais saborosas marcas de cremes de avelã, amêndoa e amendoim do mundo.', 'mission_copy_two' => 'Tratamos os ingredientes que Allah criou perfeitamente e nos apresentou da forma mais simples, atenta e delicada possível.', 'mission_copy_three' => 'Respeitamos a terra, o céu e tudo o que existe entre ambos. Como produtores de alimentos, reconhecemos a nossa responsabilidade de criar um impacto positivo.', 'mission_donation_before' => 'Todo o lucro dos produtos adquiridos neste site é dedicado em seu nome; o rendimento do nosso trabalho é dedicado, em nome do nosso querido filho', 'mission_donation_after' => 'a órfãos e famílias de órfãos.', 'mission_quote' => '«No dia da prestação de contas, até o peso de um átomo será manifesto.»', 'company_kicker' => 'CONTACTO / INFORMAÇÃO DA EMPRESA', 'company_title' => 'Estamos aqui.', 'phone_label' => 'TELEFONE', 'location_label' => 'LOCALIZAÇÃO', 'address_label' => 'MORADA', 'certificates_kicker' => 'FEITO COM CONFIANÇA', 'certificates_title' => 'Os nossos certificados<br><em>de qualidade.</em>', 'certificates_copy' => 'Consulte aqui os nossos certificados atuais.', 'certificate' => 'CERTIFICADO', 'certificates_empty' => 'Os nossos certificados de qualidade estarão disponíveis aqui em breve.'],
    'contact' => ['kicker' => 'VAMOS TRABALHAR JUNTOS', 'title' => 'Vamos dizer<br><em>olá.</em>', 'copy' => 'Contacte-nos para produtos, parcerias ou pedidos de proposta.', 'section' => 'CONTACTO', 'name' => 'Nome completo', 'email' => 'E-mail', 'message' => 'A sua mensagem', 'success' => 'Obrigado pela sua mensagem. A nossa equipa responderá em breve.'],
    'factory' => ['kicker' => 'FÁBRICA / UNIDADE DE PRODUÇÃO', 'fallback_name' => 'A nossa unidade de produção', 'address_label' => 'MORADA', 'phone_label' => 'TELEFONE', 'email_label' => 'E-MAIL', 'map_title' => 'Localização da fábrica Nuttime', 'map_copy' => 'Veja a localização<br>no Google Maps.'],
    'errors' => ['home' => 'Voltar ao início', 'products' => 'Ver produtos', '403' => ['heading' => 'Acesso negado', 'message' => 'Não tem permissão para ver esta página.'], '404' => ['heading' => 'Página não encontrada', 'message' => 'A página que procura não existe ou poderá ter sido movida.'], '419' => ['heading' => 'Sessão expirada', 'message' => 'Atualize a página e tente novamente.'], '500' => ['heading' => 'Ocorreu um problema', 'message' => 'A nossa equipa técnica foi informada. Tente novamente dentro de instantes.']],
]);
