<?php

$site = require __DIR__.'/../en/site.php';

return array_replace_recursive($site, [
    'language' => ['label' => 'اللغة', 'choose' => 'اختر اللغة'],
    'nav' => ['home' => 'الرئيسية', 'products' => 'المنتجات', 'categories' => 'الفئات', 'about' => 'من نحن', 'certificates' => 'الشهادات', 'contact' => 'اتصل بنا', 'contents' => 'القصص'],
    'footer' => ['explore' => 'اكتشف', 'contact' => 'اتصل بنا', 'social' => 'وسائل التواصل', 'reach_us' => 'تواصل معنا', 'tagline' => 'شارك ما هو جيد.', 'description' => 'فكرة طيبة من الطبيعة. اشعر بالرضا في كل لقمة.'],
    'actions' => ['open_menu' => 'فتح القائمة أو إغلاقها', 'view_product' => 'عرض المنتج', 'all_products' => 'كل المنتجات', 'scroll_down' => 'مرّر للأسفل', 'discover' => 'اكتشف', 'discover_story' => 'اكتشف قصتنا', 'open_document' => 'فتح المستند', 'view_document' => 'عرض المستند', 'contact_us' => 'اتصل بنا', 'get_directions' => 'الحصول على الاتجاهات', 'view_map' => 'عرض على الخريطة', 'send_message' => 'إرسال الرسالة', 'learn_more' => 'اكتشف', 'close' => 'إغلاق'],
    'catalog' => ['default_category' => 'تشكيلة Nuttime', 'category' => 'الفئة', 'products_count' => ':count منتجات', 'category_count' => 'الفئة / :count منتجات', 'empty' => 'ستتوفر تشكيلتنا هنا قريباً.', 'category_empty' => 'لا توجد منتجات نشطة في هذه الفئة بعد.'],
    'home' => ['banners_label' => 'تشكيلات Nuttime', 'banner_one_kicker' => 'جيل جديد من المذاق', 'banner_one_title' => 'اكتشف الفستق<br>من جديد.', 'banner_two_kicker' => 'لكل يوم', 'banner_two_title' => 'اشعر بالرضا<br>في ملعقة واحدة.', 'intro' => 'نحوّل أجود المكسرات والمكونات البسيطة إلى <em>أمتع لحظات يومك.</em>', 'featured_kicker' => 'مختارة بعناية', 'featured_title' => 'نكهات<br><em>مميزة.</em>', 'categories_kicker' => 'الفئات', 'categories_title' => 'اعثر على ما يمنحك<br><em>شعوراً طيباً.</em>', 'story_kicker' => 'من نحن', 'story_title' => 'منتجات طيبة،<br><em>مشاعر طيبة،</em><br>وحياة طيبة.', 'story_copy' => 'تعد Nuttime الطابع الطبيعي للمكسرات المختارة بعناية لتكتشفه كل يوم من جديد.', 'quality_kicker' => 'صُنع بثقة', 'quality_title' => 'الجودة في<br><em>كل تفصيل.</em>', 'social_kicker' => 'إلهام يومي', 'social_title' => 'تابع Nuttime<br><em>عن قرب.</em>', 'instagram' => 'فتح Instagram'],
    'final_cta' => ['kicker' => 'تعرّف إلى NUTTIME', 'title' => 'رفيق طيب لكل<br><em>لحظة من اليوم.</em>'],
    'product' => ['detail_label' => 'تشكيلة Nuttime', 'detail_copy' => 'مكونات طبيعية وإنتاج متقن وتجربة مذاق تمنحك شعوراً طيباً.', 'whatsapp' => 'اسأل عبر WhatsApp', 'image' => 'صورة المنتج :number', 'breadcrumbs' => 'مسار المنتج', 'ingredients_kicker' => 'معلومات المنتج', 'ingredients' => 'المكونات', 'allergens' => 'معلومات مسببات الحساسية: ', 'nutrition_kicker' => 'القيم الغذائية', 'nutrition' => 'نظرة سريعة', 'packaging_kicker' => 'B2B / الخدمات اللوجستية', 'packaging' => 'التعبئة والخدمات اللوجستية', 'packaging_copy' => 'تُعرض تفاصيل تعبئة التجزئة والتعبئة الصناعية بشكل منظم لتخطيط الشحنات.'],
    'static' => ['about_kicker' => 'عن NUTTIME', 'about_title' => 'من <em>نحن؟</em>', 'about_copy' => 'شركتنا مشروع عائلي صغير تملكه وتديره عائلة من أربعة أفراد. انطلقنا بفكرة السعي إلى إنتاج أغذية عالية الجودة. نطوّر جميع منتجاتنا لتكون لذيذة ومغذية.', 'who_kicker' => 'من نحن', 'who_title' => 'مشروع عائلي صغير.', 'who_copy_one' => 'رغم أننا نمونا 400 مرة خلال عشر سنوات، ما زلنا نشعر أننا مشروع عائلي صغير.', 'who_copy_two' => 'هذا الشعور جيد بالنسبة لنا.', 'mission_kicker' => 'مهمتنا', 'mission_title' => 'رعاية ما هو طيب بعناية.', 'mission_copy_one' => 'نفخر بأن نكون جزءاً مهماً من الحل لبناء مجتمع أكثر سعادة وصحة وشمولاً وأماناً للجميع، ونعمل لنصبح إحدى ألذ علامات كريمة البندق واللوز والفول السوداني في العالم.', 'mission_copy_two' => 'نتعامل مع المكونات التي خلقها الله بإتقان وقدمها لنا بأكبر قدر ممكن من البساطة والعناية والدقة.', 'mission_copy_three' => 'نحترم الأرض والسماء وكل ما بينهما. وبصفتنا منتجاً غذائياً، ندرك مسؤوليتنا في السعي لإحداث أثر إيجابي.', 'mission_donation_before' => 'يُخصص كامل ربح المنتجات المشتراة عبر هذا الموقع باسمكم؛ ويُخصص دخل عملنا باسم ابننا الحبيب', 'mission_donation_after' => 'للأيتام وعائلاتهم.', 'mission_quote' => '«في يوم الحساب سيظهر حتى وزن الذرة».', 'company_kicker' => 'الاتصال / معلومات الشركة', 'company_title' => 'نحن هنا.', 'phone_label' => 'الهاتف', 'location_label' => 'الموقع', 'address_label' => 'العنوان', 'certificates_kicker' => 'صُنع بثقة', 'certificates_title' => 'شهاداتنا<br><em>للجودة.</em>', 'certificates_copy' => 'اطّلع على شهاداتنا الحالية هنا.', 'certificate' => 'شهادة', 'certificates_empty' => 'ستتوفر شهادات الجودة لدينا هنا قريباً.'],
    'contact' => ['kicker' => 'لنعمل معاً', 'title' => 'لنقل<br><em>مرحباً.</em>', 'copy' => 'تواصل معنا بخصوص المنتجات أو الشراكات أو طلبات العروض.', 'section' => 'اتصل بنا', 'name' => 'الاسم الكامل', 'email' => 'البريد الإلكتروني', 'message' => 'رسالتك', 'success' => 'شكراً لرسالتك. سيتواصل معك فريقنا قريباً.'],
    'factory' => ['kicker' => 'المصنع / منشأة الإنتاج', 'fallback_name' => 'منشأة الإنتاج لدينا', 'address_label' => 'العنوان', 'phone_label' => 'الهاتف', 'email_label' => 'البريد الإلكتروني', 'map_title' => 'موقع مصنع Nuttime', 'map_copy' => 'اعرض الموقع<br>على Google Maps.'],
    'errors' => ['home' => 'العودة إلى الرئيسية', 'products' => 'عرض المنتجات', '403' => ['heading' => 'تم رفض الوصول', 'message' => 'ليس لديك صلاحية لعرض هذه الصفحة.'], '404' => ['heading' => 'الصفحة غير موجودة', 'message' => 'الصفحة التي تبحث عنها غير موجودة أو ربما تم نقلها.'], '419' => ['heading' => 'انتهت الجلسة', 'message' => 'يرجى تحديث الصفحة والمحاولة مجدداً.'], '500' => ['heading' => 'حدثت مشكلة', 'message' => 'تم إبلاغ فريقنا التقني. يرجى المحاولة مرة أخرى قريباً.']],
]);
