@extends('layouts.app')

@section('content')
@php($gallery = collect([$product['image'] ?? null, ...($product['gallery'] ?? [])])->filter()->values())
@php($featureTags = collect($product['feature_tags'] ?? [])->filter()->values())
@php($technicalDetails = collect([__('site.product.detail_label') => $product['weight_grams'] ? $product['weight_grams'].' g' : null, 'SKU' => $product['sku'] ?? null, '%' => $product['primary_ingredient_percentage'] ? rtrim(rtrim((string) $product['primary_ingredient_percentage'], '0'), '.').'%' : null])->filter())

<nav class="container breadcrumb" aria-label="Ürün yolu">@foreach($breadcrumbs as $item)<a href="{{ $item['item'] }}">{{ $item['name'] }}</a>@if(! $loop->last)<span aria-hidden="true">/</span>@endif @endforeach</nav>

<section class="product-stage"><div class="container product-stage__grid"><div class="product-stage__visual" x-data="{ active: 0, images: @js($gallery) }"><div class="product-stage__surface" style="--product-tint:{{ $product['accent'] ?? '#d8b768' }}">@if($gallery->isNotEmpty())<img :src="images[active]" alt="{{ $product['image_alt'] ?: $product['name'] }}" width="1707" height="2560" loading="eager" fetchpriority="high" decoding="async">@endif<span class="product-stage__monogram" aria-hidden="true">nt</span></div>@if($gallery->count() > 1)<div class="product-stage__thumbs" role="tablist" aria-label="{{ $product['name'] }}"><span>01 — {{ str_pad((string) $gallery->count(), 2, '0', STR_PAD_LEFT) }}</span>@foreach($gallery as $index => $image)<button type="button" @click="active={{ $index }}" :class="{'is-active':active==={{ $index }}}" :aria-selected="active==={{ $index }}" aria-label="{{ __('site.product.image', ['number' => $index + 1]) }}">{{ str_pad((string) ($index + 1), 2, '0', STR_PAD_LEFT) }}</button>@endforeach</div>@endif</div><div class="product-stage__copy"><p class="kicker">{{ $product['category'] }}</p><h1>{{ $product['name'] }}</h1>@if($featureTags->isNotEmpty())<ul class="product-stage__tags" aria-label="{{ $product['name'] }}"><li>{{ $featureTags->implode(' · ') }}</li></ul>@endif<p class="product-stage__lead">{{ $product['description'] }}</p>@if($technicalDetails->isNotEmpty())<dl class="product-stage__facts">@foreach($technicalDetails as $label => $value)<div><dt>{{ $label }}</dt><dd>{{ $value }}</dd></div>@endforeach</dl>@endif@if(!empty($settings['whatsapp']))<a class="button button--ink" href="https://wa.me/{{ preg_replace('/\D/', '', $settings['whatsapp']) }}">{{ __('site.product.whatsapp') }} <span>↗</span></a>@else<a class="button button--ink" href="{{ app(\App\Support\LocalizedUrl::class)->route('contact') }}">{{ __('site.actions.contact_us') }} <span>↗</span></a>@endif</div></div></section>

@if(collect($product['packaging_details'] ?? [])->isNotEmpty() || collect($product['nutrition_facts'] ?? [])->isNotEmpty())<section class="product-data"><div class="container product-data__grid">@if(collect($product['packaging_details'] ?? [])->isNotEmpty())<div><p class="kicker">{{ __('site.product.detail_label') }}</p><h2>{{ $product['name'] }}</h2><dl>@foreach($product['packaging_details'] as $label => $value)@if(filled($value))<div><dt>{{ $label }}</dt><dd>{{ $value }}</dd></div>@endif@endforeach</dl></div>@endif@if(collect($product['nutrition_facts'] ?? [])->isNotEmpty())<div><p class="kicker">{{ __('site.product.detail_label') }}</p><h2>{{ $product['category'] }}</h2><dl>@foreach($product['nutrition_facts'] as $label => $value)@if(filled($value))<div><dt>{{ $label }}</dt><dd>{{ $value }}</dd></div>@endif@endforeach</dl></div>@endif</div></section>@endif

@if($gallery->count() > 1)<section class="product-gallery"><div class="container"><x-section-heading :kicker="$product['category']" :title="$product['name']" /><div class="product-gallery__grid">@foreach($gallery as $index => $image)<figure class="product-gallery__item product-gallery__item--{{ $index % 3 }}"><img src="{{ $image }}" alt="{{ $product['name'] }}" width="1707" height="2560" loading="lazy" decoding="async"></figure>@endforeach</div></div></section>@endif

@if(count($related))<section class="related-selection"><div class="container"><x-section-heading :kicker="__('site.product.related_kicker')" :title="__('site.product.related_title')" rich-title /><div class="related-selection__grid">@foreach($related as $index => $item)<x-product-card :product="$item" :index="$index" :variant="$index === 0 ? 'hero' : 'default'" />@endforeach</div></div></section>@endif
@endsection
