<?php

return [
    'language' => ['label' => 'Dil', 'choose' => 'Dil seçin'],
    'nav' => ['home' => 'Ana sayfa', 'products' => 'Ürünler', 'categories' => 'Kategoriler', 'about' => 'Hakkımızda', 'certificates' => 'Sertifikalar', 'contact' => 'İletişim', 'contents' => 'İçerikler'],
    'footer' => ['explore' => 'Keşfet', 'contact' => 'İletişim', 'social' => 'Sosyal', 'reach_us' => 'Bize ulaşın', 'tagline' => 'İyi olanı paylaş.', 'description' => 'Doğadan gelen iyi fikir. Her lokmada iyi hisset.'],
    'actions' => ['skip_to_content' => 'İçeriğe geç', 'open_menu' => 'Menüyü aç/kapat', 'view_product' => 'Ürünü incele', 'all_products' => 'Tüm ürünler', 'scroll_down' => 'Aşağı kaydır', 'discover' => 'Keşfet', 'discover_story' => 'Hikâyemizi keşfet', 'open_document' => 'Belgeyi aç', 'view_document' => 'Belgeyi görüntüle', 'contact_us' => 'Bizimle iletişime geç', 'get_directions' => 'Yol tarifi al', 'view_map' => 'Haritada gör', 'send_message' => 'Mesajı gönder', 'learn_more' => 'İncele', 'close' => 'Kapat'],
    'catalog' => ['default_category' => 'Nuttime seçkisi', 'category' => 'kategorisi', 'products_count' => ':count ürün', 'category_count' => 'KATEGORİ / :count ÜRÜN', 'empty' => 'Seçkimiz yakında burada yer alacak.', 'category_empty' => 'Bu kategoride henüz aktif ürün bulunmuyor.'],
    'meta' => [
        'home' => ['title' => 'Nuttime', 'description' => 'Nuttime ile yalın içeriklerden gelen yoğun kuruyemiş lezzetlerini keşfedin.'],
        'products' => ['title' => 'Nuttime Ürünleri', 'description' => 'Nuttime kuruyemiş ezmeleri ve özenle hazırlanan ürün seçkisini keşfedin.'],
        'about' => ['title' => 'Nuttime Hakkında', 'description' => 'Nuttime’ın üretim yaklaşımını ve kalite odağını keşfedin.'],
        'certificates' => ['title' => 'Nuttime Sertifikaları', 'description' => 'Nuttime kalite belgeleri ve üretim standartlarını inceleyin.'],
        'contact' => ['title' => 'Nuttime İletişim', 'description' => 'İş birliği ve ürün talepleriniz için Nuttime ile iletişime geçin.'],
        'contents' => ['title' => 'Nuttime İçerikler', 'description' => 'Tarifler, haberler ve Nuttime dünyasından içerikler.'],
    ],
    'hero' => [
        'yer-fistigi-ezmesi' => ['eyebrow' => 'NUTTIME • %52 YER FISTIĞI', 'title' => 'YER FISTIĞININ EN YOĞUN HALİ'],
        'findik-kremasi' => ['eyebrow' => 'NUTTIME • %45 FINDIK', 'title' => 'FINDIĞIN KAVRULMUŞ ZENGİNLİĞİ'],
        'antep-fistikli-kremasi' => ['eyebrow' => 'NUTTIME • %42 ANTEP FISTIĞI', 'title' => 'ANTEP FISTIĞININ EN YOĞUN HALİ'],
        'badem-unu' => ['eyebrow' => 'NUTTIME • %45 BADEM', 'title' => 'BADEMİN ZARİF VE YOĞUN DOKUSU'],
        'seker-ilavesiz-yer-fistigi-ezmesi' => ['eyebrow' => 'NUTTIME • ŞEKER İLAVESİZ • %72', 'title' => 'DAHA SADE, DAHA YOĞUN FISTIK'],
        'hindistan-cevizi-ezmesi' => ['eyebrow' => 'NUTTIME • %42 HİNDİSTAN CEVİZİ', 'title' => 'FERAH VE KREMAMSI BİR DOKU'],
    ],
    'home' => ['banners_label' => 'Nuttime seçkileri', 'banner_one_kicker' => 'YENİ NESİL LEZZET', 'banner_one_title' => 'Antep fıstığını<br>yeniden keşfet.', 'banner_two_kicker' => 'HER GÜNE EŞLİK EDER', 'banner_two_title' => 'Bir kaşıkta<br>iyi his.', 'intro' => 'İyi kuruyemişleri, yalın içeriklerle <em>günün en keyifli anına</em> dönüştürüyoruz.', 'featured_kicker' => 'ÖZENLE SEÇTİK', 'featured_title' => 'Öne çıkan<br><em>lezzetler.</em>', 'categories_kicker' => 'KATEGORİLER', 'categories_title' => 'İyi olanı<br><em>bul.</em>', 'moment_kicker' => 'BİR KAVANOZDAN DAHA FAZLASI', 'moment_title' => 'Her zevke, her ritme<br><em>iyi eşlik eder.</em>', 'story_kicker' => 'BİZ KİMİZ?', 'story_title' => 'İyi ürün,<br><em>iyi his,</em><br>iyi bir hayat.', 'story_copy' => 'Nuttime, özenle seçilmiş kuruyemişlerin doğal karakterini her gün yeniden keşfetmeniz için hazırlar.', 'quality_kicker' => 'GÜVENLE ÜRETİYORUZ', 'quality_title' => 'Kalite, her<br><em>detayda.</em>', 'social_kicker' => 'GÜNLÜK İLHAM', 'social_title' => 'Nuttimeı<br><em>yakından takip edin.</em>', 'instagram' => 'Instagramda aç'],
    'final_cta' => ['kicker' => 'NUTTIME İLE TANIŞIN', 'title' => 'Günün her anına<br><em>iyi eşlik et.</em>'],
    'product' => ['detail_label' => 'Nuttime seçkisi', 'detail_copy' => 'Doğal içerikler, özenli üretim ve iyi hissettiren bir lezzet deneyimi.', 'whatsapp' => 'WhatsApp ile bilgi al', 'related_kicker' => 'BUNLARI DA KEŞFEDİN', 'related_title' => 'Seçkiden<br><em>diğer lezzetler.</em>', 'image' => 'Ürün görseli :number', 'breadcrumbs' => 'Ürün yolu', 'ingredients_kicker' => 'ÜRÜN BİLGİSİ', 'ingredients' => 'İçindekiler', 'allergens' => 'Alerjen bilgisi: ', 'nutrition_kicker' => 'BESİN DEĞERLERİ', 'nutrition' => 'Bir bakışta değerler', 'packaging_kicker' => 'B2B / LOJİSTİK', 'packaging' => 'Ambalaj & lojistik', 'packaging_copy' => 'Perakende ve endüstriyel ambalaj bilgileri, sevkiyat planlaması için yapılandırılmış olarak sunulur.', 'nutrition_fields' => ['energy' => 'Enerji (kJ/kcal)', 'fat' => 'Yağ (%)', 'saturated_fat' => 'Doymuş yağ asitleri (g)', 'trans_fat' => 'Trans yağ (g)', 'carbohydrates' => 'Karbonhidrat (g)', 'sugar' => 'Şeker (g)', 'fibre' => 'Lif (g)', 'protein' => 'Protein (g)', 'salt' => 'Tuz (g)'], 'packaging_groups' => ['general' => 'Ambalaj', 'jar' => 'Kavanoz', 'carton' => 'Koli', 'pallet' => 'Koli paleti', 'industrial' => 'Endüstriyel kova / Europalette', 'dimensions' => 'Teknik ölçüler'], 'packaging_fields' => ['net_weight' => 'Net ağırlık', 'gross_weight' => 'Brüt ağırlık', 'diameter' => 'Çap', 'height' => 'Yükseklik', 'units' => 'Koli içi adedi', 'buckets_on_pallet' => 'Paletteki kova adedi', 'dimensions' => 'Ölçüler', 'dimensions_inches' => 'İnç karşılığı', 'cartons' => 'Paletteki koli adedi', 'type' => 'Palet tipi', 'loaded_height' => 'Palet dolu yüksekliği', 'loaded_height_inches' => 'İnç karşılığı', 'd1' => 'D1', 'd2' => 'D2', 'd3' => 'D3', 'h' => 'H']],
    'static' => ['about_kicker' => 'NUTTIME HAKKINDA', 'about_title' => 'Biz <em>kimiz?</em>', 'about_copy' => 'Firmamız, dört kişilik bir ailenin sahibi olduğu ve işlettiği küçük bir aile işletmesidir. Üstün kaliteli gıdalar üretmek için çabalama fikriyle yola çıktık. Ürünlerimizin tamamını lezzetli ve besleyici olacak şekilde geliştiriyoruz.', 'about_lead' => 'Beslenmenin sağlığın temeli olduğuna inanıyoruz.', 'who_kicker' => 'BİZ KİMİZ?', 'who_title' => 'Küçük bir aile işletmesi.', 'who_copy_one' => 'Bu inançla çıktığımız yolda 10 yılda 400 kat büyümüş olsak da hâlâ kendimizi küçük bir aile işletmesi gibi hissediyoruz.', 'who_copy_two' => 'Bu his bize iyi geliyor.', 'mission_kicker' => 'MİSYONUMUZ', 'mission_title' => 'İyi olanı özenle büyütmek.', 'mission_copy_one' => 'Herkes için daha mutlu, daha sağlıklı, daha kapsayıcı ve daha güvenli bir toplum oluşturma yolunda çözümün önemli bir parçası olmaktan ve dünyanın en lezzetli fındık, badem ve yer fıstığı ezmesi markalarından biri olma hedefiyle çalışmaktan gurur duyuyoruz.', 'mission_copy_two' => 'Allah’ın mükemmel yarattığı ve bize sunduğu malzemeleri mümkün olduğunca basit, özenli ve incelikli bir şekilde ele alıyoruz.', 'mission_copy_three' => 'Yere, göğe ve arasındaki her şeye saygı duyuyoruz. Bir gıda üreticisi olarak olumlu bir etki oluşturmak için çabalama sorumluluğumuzun bilincindeyiz.', 'mission_donation_before' => 'Bu site üzerinden satın aldığınız ürünlerden elde edilen kârın tamamı sizin adınıza; emek kısmından elde edilen gelir ise biricik oğlumuz', 'mission_donation_name' => 'Oğuzhan Kuş', 'mission_donation_after' => 'adına yetimlere ve yetim ailelerine vakfedilmektedir.', 'mission_quote' => '“Hesap gününde zerre miskal ayan beyan olacaktır.”', 'company_kicker' => 'İLETİŞİM / FİRMA BİLGİLERİ', 'company_title' => 'Buradayız.', 'phone_label' => 'TELEFON', 'location_label' => 'KONUM', 'address_label' => 'ADRES', 'certificates_kicker' => 'GÜVENLE ÜRETİYORUZ', 'certificates_title' => 'Kalite<br><em>belgelerimiz.</em>', 'certificates_copy' => 'Güncel belgelerimizi buradan inceleyebilirsiniz.', 'certificate' => 'SERTİFİKA', 'certificates_empty' => 'Kalite belgelerimiz yakında burada yer alacak.'],
    'contact' => ['kicker' => 'BİRLİKTE ÇALIŞALIM', 'title' => 'Merhaba<br><em>diyelim.</em>', 'copy' => 'Ürünlerimiz, iş birlikleri veya teklif talepleriniz için bize ulaşın.', 'section' => 'İLETİŞİM', 'name' => 'Ad soyad', 'email' => 'E-posta', 'message' => 'Mesajınız', 'success' => 'Mesajınız için teşekkür ederiz. Ekibimiz en kısa sürede size dönüş yapacaktır.'],
    'factory' => ['kicker' => 'FABRİKA / ÜRETİM TESİSİ', 'fallback_name' => 'Üretim tesisimiz', 'address_label' => 'ADRES', 'phone_label' => 'TELEFON', 'email_label' => 'E-POSTA', 'map_title' => 'Nuttime fabrika konumu', 'map_copy' => 'Konumu Google Maps’te<br>görüntüleyin.'],
    'errors' => ['home' => 'Ana sayfaya dön', 'products' => 'Ürünleri incele', '403' => ['heading' => 'Erişim yok', 'message' => 'Bu sayfayı görüntüleme yetkiniz bulunmuyor.'], '404' => ['heading' => 'Sayfa bulunamadı', 'message' => 'Aradığınız sayfa mevcut değil veya taşınmış olabilir.'], '419' => ['heading' => 'Oturum süresi doldu', 'message' => 'Lütfen sayfayı yenileyip tekrar deneyin.'], '500' => ['heading' => 'Bir sorun oluştu', 'message' => 'Teknik ekibimiz bilgilendirildi. Lütfen kısa süre sonra tekrar deneyin.']],
];
